### ISSUE TITLE
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by crise2019** [bytedance/Fastbot_Android#1]
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
        at android.os.Handler.<init>(Handler.java:204)
        at android.os.Handler.<init>(Handler.java:118)
        at com.meizu.nightmode.MzNightModeManager.<init>(MzNightModeManager.java:169)
        at com.meizu.nightmode.MzNightModeManager.getDefault(MzNightModeManager.java:362)
        at android.graphics.BaseCanvas.<init>(BaseCanvas.java:1072)
        at android.graphics.Canvas.<init>(Canvas.java:114)
        at android.app.UiAutomation.takeScreenshot(UiAutomation.java:741)
        at com.android.commands.monkey.y.H(SourceFile:1269)
        at com.android.a.a.e.c(SourceFile:3176)
        at com.android.a.a.b.b(SourceFile:236)
        at com.android.a.a.b.a(SourceFile:226)
        at com.android.commands.monkey.y.y(SourceFile:680)
        at com.android.commands.monkey.y.l(SourceFile:1239)
        at com.android.commands.monkey.Monkey.f(SourceFile:1861)
        at com.android.commands.monkey.Monkey.a(SourceFile:1105)
        at com.android.commands.monkey.Monkey.main(SourceFile:827)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)

**Comment by zhangzhao4444** [comment]
可以用 2.2.1.1207.1725_git版本试一下是否解决？

**Comment by fuzecheng** [comment]
> 可以用 2.2.1.1207.1725_git版本试一下是否解决？

是开发的同学吗，有些问题想请教一下 ，方便加个QQ或者微信吗

**Comment by zhangzhao4444** [comment]
qq 77227005

**Comment by zhangzhao4444** [comment]
已验证 修复
