### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by hhhaiai** [bytedance/Fastbot_Android#104]
```
[Fastbot][2021-11-09 16:17:21.740] // Eventid: 3
[Fastbot][2021-11-09 16:17:21.744] // Monkey is over!
[Fastbot][2021-11-09 16:17:21.744] :Sending rotation degree=0, persist=false
[Fastbot][2021-11-09 16:17:21.756] Internal error
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/GsonBuilder;
	at com.android.commands.monkey.fastbot.client.GsonIface.<clinit>(SourceFile:28)
	at com.android.commands.monkey.fastbot.client.Operate.fromJson(SourceFile:54)
	at com.bytedance.fastbot.AiClient.l(SourceFile:1137)
	at com.android.commands.monkey.x.z(SourceFile:848)
	at com.android.commands.monkey.x.k(SourceFile:395)
	at com.android.commands.monkey.Monkey.f(SourceFile:1510)
	at com.android.commands.monkey.Monkey.a(SourceFile:867)
	at com.android.commands.monkey.Monkey.main(SourceFile:458)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:362)
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
	... 10 more
[Fastbot][2021-11-09 16:17:21.758] Please report this bug issue to github
▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄
▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░▌ ▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌
▐░█▀▀▀▀▀▀▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀▀▀  ▀▀▀▀█░█▀▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀█░▌ ▀▀▀▀█░█▀▀▀▀
▐░▌          ▐░▌       ▐░▌▐░▌               ▐░▌     ▐░▌       ▐░▌▐░▌       ▐░▌     ▐░▌
▐░█▄▄▄▄▄▄▄▄▄ ▐░█▄▄▄▄▄▄▄█░▌▐░█▄▄▄▄▄▄▄▄▄      ▐░▌     ▐░█▄▄▄▄▄▄▄█░▌▐░▌       ▐░▌     ▐░▌
▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌     ▐░▌     ▐░░░░░░░░░░▌ ▐░▌       ▐░▌     ▐░▌
▐░█▀▀▀▀▀▀▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌ ▀▀▀▀▀▀▀▀▀█░▌     ▐░▌     ▐░█▀▀▀▀▀▀▀█░▌▐░▌       ▐░▌     ▐░▌
▐░▌          ▐░▌       ▐░▌          ▐░▌     ▐░▌     ▐░▌       ▐░▌▐░▌       ▐░▌     ▐░▌
▐░▌          ▐░▌       ▐░▌ ▄▄▄▄▄▄▄▄▄█░▌     ▐░▌     ▐░█▄▄▄▄▄▄▄█░▌▐░█▄▄▄▄▄▄▄█░▌     ▐░▌
▐░▌          ▐░▌       ▐░▌▐░░░░░░░░░░░▌     ▐░▌     ▐░░░░░░░░░░▌ ▐░░░░░░░░░░░▌     ▐░▌
 ▀            ▀         ▀  ▀▀▀▀▀▀▀▀▀▀▀       ▀       ▀▀▀▀▀▀▀▀▀▀   ▀▀▀▀▀▀▀▀▀▀▀       ▀
[Fastbot][2021-11-09 16:17:22.295]  @Version: 2.2.01.1101.2108-git
[Fastbot][2021-11-09 16:17:22.310] // Monkey: seed=1636658379438 count=1000
```

**Comment by geron-cn** [comment]
参照 https://github.com/bytedance/Fastbot_Android/blob/main/handbook-cn.md  常见问题 6
