### ISSUE TITLE
进入app首页后报错/data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by FrankWangJQ** [bytedance/Fastbot_Android#107]
[Fastbot][2021-11-21 23:52:19.935] // phone info： Xiaomi_M2007J17C_10
[Fastbot][2021-11-21 23:52:19.936] // runing fastbot
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at java.io.FileReader.<init>(FileReader.java:58)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
        at android.content.res.Resources.<init>(Resources.java:285)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
        at android.content.res.Resources.getSystem(Resources.java:206)
        at android.app.ActivityManager.isHighEndGfx(ActivityManager.java:936)
        at android.app.ActivityThread.systemMain(ActivityThread.java:7369)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.commands.monkey.g.b.ao(SourceFile:46)
        at com.android.commands.monkey.framework.AndroidDevice.a(SourceFile:113)
        at com.android.commands.monkey.Monkey.a(SourceFile:794)
        at com.android.commands.monkey.Monkey.main(SourceFile:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        ... 21 more
[Fastbot][2021-11-21 23:52:20.088] InputMethod ID: com.iflytek.inputmethod.miui/.FlyIME
[Fastbot][2021-11-21 23:52:20.089] InputMethod ID: com.sohu.inputmethod.sogou.xiaomi/.SogouIME
[Fastbot][2021-11-21 23:52:20.101] // device serial number is 1c579cec
[Fastbot][2021-11-21 23:52:20.139] // device uuid is a549c92e-b4ef-4233-af7f-bcc0aaad1ec2
[Fastbot][2021-11-21 23:52:23.135]

[Fastbot][2021-11-21 23:52:23.143] // the top activity is com.miui.home.launcher.Launcher, not testing app, need inject restart app
[Fastbot][2021-11-21 23:52:23.147] Switch: #Intent;action=android.intent.action.MAIN;category=android.intent.category.LAUNCHER;launchFlags=0x10200000;component=com.universal.medical.patient.dev/com.universal.medical.patient.activity.SplashActivity;end
[Fastbot][2021-11-21 23:52:23.171] // the top activity is com.universal.medical.patient.activity.SplashActivity, phone capture activity is com.android.camera.Camera
[Fastbot][2021-11-21 23:52:23.172]     // Allowing start of Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.universal.medical.patient.dev/com.universal.medical.patient.activity.SplashActivity } in package com.universal.medical.patient.dev
[Fastbot][2021-11-21 23:52:23.176] // the top activity is com.universal.medical.patient.activity.SplashActivity, phone capture activity is com.android.camera.Camera
[Fastbot][2021-11-21 23:52:23.177]     // Allowing start of Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.universal.medical.patient.dev/com.universal.medical.patient.activity.SplashActivity } in package com.universal.medical.patient.dev
[Fastbot][2021-11-21 23:52:23.203] // current activity is com.universal.medical.patient.activity.MainActivity
[Fastbot][2021-11-21 23:52:23.239] Sleeping for 2000 milliseconds
[Fastbot][2021-11-21 23:52:25.277] // Eventid: 3
[Fastbot]*** ERROR *** Error: Could not load library!
java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/local/tmp/arm64-v8a/libfastbot_native.so" not found
        at java.lang.Runtime.load0(Runtime.java:938)
        at java.lang.System.load(System.java:1631)
        at com.bytedance.fastbot.AiClient.<clinit>(SourceFile:42)
        at com.bytedance.fastbot.AiClient.l(SourceFile:111)
        at com.android.commands.monkey.x.z(SourceFile:848)
        at com.android.commands.monkey.x.k(SourceFile:395)
        at com.android.commands.monkey.Monkey.f(SourceFile:1510)
        at com.android.commands.monkey.Monkey.a(SourceFile:867)
        at com.android.commands.monkey.Monkey.main(SourceFile:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
[Fastbot][2021-11-21 23:52:25.343] // Error: Could not load native library!
[Fastbot][2021-11-21 23:52:25.343] Please report this bug issue to github

**Comment by jianchen10** [comment]
+1，遇到同样的问题

**Comment by rockcaostar** [comment]
XiaoMi手机跑报错 和主题有关系，应该从手机设置里禁用 不知道能否解决

**Comment by pxrgod** [comment]
这个可以成功？有试过么
> XiaoMi手机跑报错 和主题有关系，应该从手机设置里禁用 不知道能否解决

**Comment by zhangzhao4444** [comment]
没有影响，可以忽略
