### ISSUE TITLE
配置 “max.widget.black” 功能 出现异常

### ISSUE THREAD

**Issue by xiaxiayige** [bytedance/Fastbot_Android#109]
`[Fastbot][2021-11-24 20:44:40.564] Internal error
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@bc99ac2already registered!
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2397)
        at android.os.Parcel.createException(Parcel.java:2373)
        at android.os.Parcel.readException(Parcel.java:2356)
        at android.os.Parcel.readException(Parcel.java:2298)
        at android.view.accessibility.IAccessibilityManager$Stub$Proxy.registerUiTestAutomationService(IAccessibilityManager.java:739)
        at android.app.UiAutomationConnection.registerUiTestAutomationServiceLocked(UiAutomationConnection.java:456)
        at android.app.UiAutomationConnection.connect(UiAutomationConnection.java:106)
        at android.app.UiAutomation.connect(UiAutomation.java:248)
        at android.app.UiAutomation.connect(UiAutomation.java:224)
        at com.android.commands.monkey.x.<init>(SourceFile:1259)
        at com.android.commands.monkey.Monkey.a(SourceFile:797)
        at com.android.commands.monkey.Monkey.main(SourceFile:454)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:419)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.accessibility.UiAutomationManager.registerUiTestAutomationServiceLocked(UiAutomationManager.java:97)
        at com.android.server.accessibility.AccessibilityManagerService.registerUiTestAutomationService(AccessibilityManagerService.java:885)
        at android.view.accessibility.IAccessibilityManager$Stub.onTransact(IAccessibilityManager.java:371)
        at android.os.Binder.execTransactInternal(Binder.java:1161)
        at android.os.Binder.execTransact(Binder.java:1130)

[Fastbot][2021-11-24 20:44:40.566] Please report this bug issue to github`

**max.widget.black**

`[
{
    "activity":"com.xxx.app.xxx.ui.xxx.login.main.LoginActivity",
    "xpath": "//*[@resource-id='com.xxx.xxx/tv_phone_code']"
}
]`

**Comment by geron-cn** [comment]
与配置无关， 可查看 #46
