### ISSUE TITLE
华为P20 Pro Android 10运行最新的fastbot报错

### ISSUE THREAD

**Issue by wywincl** [bytedance/Fastbot_Android#113]
[Fastbot][2021-12-13 13:43:08.669] Internal error
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/GsonBuilder;
	at com.android.commands.monkey.fastbot.client.GsonIface.<clinit>(SourceFile:28)
	at com.android.commands.monkey.fastbot.client.Operate.fromJson(SourceFile:54)
	at com.bytedance.fastbot.AiClient.l(SourceFile:1137)
	at com.android.commands.monkey.x.z(SourceFile:848)
	at com.android.commands.monkey.x.k(SourceFile:395)
	at com.android.commands.monkey.Monkey.f(SourceFile:1510)
	at com.android.commands.monkey.Monkey.a(SourceFile:867)
	at com.android.commands.monkey.Monkey.main(SourceFile:458)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
	... 10 more
[Fastbot][2021-12-13 13:43:08.671] Please report this bug issue to github
(base) ➜  Fastbot

**Comment by wywincl** [comment]
不是问题，没有引用/sdcard/fastbot-thirdpart.jar
