### ISSUE TITLE
当程序遇到的应用没有点击事件（只有遥控器按键 事件），执行时报错；

### ISSUE THREAD

**Issue by yuanlishen** [bytedance/Fastbot_Android#122]
```log
[Fastbot][2022-01-13 11:41:32.740] Internal error
java.lang.NoSuchMethodError: android.os.IPowerManager.isInteractive
	at com.android.commands.monkey.framework.AndroidDevice.aj(SourceFile:244)
	at com.android.commands.monkey.Monkey.a(SourceFile:795)
	at com.android.commands.monkey.Monkey.main(SourceFile:458)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:243)
	at dalvik.system.NativeStart.main(Native Method)
[Fastbot][2022-01-13 11:41:32.745] Please report this bug issue to github
```

**Comment by geron-cn** [comment]
hello， 请提供更多信息， 包含： 系统版本/ 机器型号 等详细信息。

**Comment by zhangzhao4444** [comment]
未有更多信息
