### ISSUE TITLE
使用fastbot工具执行时报错Internal error

### ISSUE THREAD

**Issue by yusandy0920** [bytedance/Fastbot_Android#123]
[Fastbot][2022-01-17 12:30:28.257] // phone info： Google_Pixel XL_8.1.0
[Fastbot][2022-01-17 12:30:28.261] // runing fastbot
[Fastbot][2022-01-17 12:30:28.418] InputMethod ID: com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME
[Fastbot][2022-01-17 12:30:28.420] InputMethod ID: com.google.android.inputmethod.pinyin/.PinyinIME
[Fastbot][2022-01-17 12:30:28.424] InputMethod ID: com.google.android.googlequicksearchbox/com.google.android.voicesearch.ime.VoiceInputMethodService
[Fastbot][2022-01-17 12:30:28.427] InputMethod ID: com.google.android.inputmethod.korean/.KoreanIme
[Fastbot][2022-01-17 12:30:28.429] InputMethod ID: com.google.android.inputmethod.japanese/.MozcService
[Fastbot][2022-01-17 12:30:28.444] // device serial number is HT7550203591
[Fastbot][2022-01-17 12:30:28.466] Internal error
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@ac12bf4already registered!
        at android.os.Parcel.readException(Parcel.java:2012)
        at android.os.Parcel.readException(Parcel.java:1950)
        at android.view.accessibility.IAccessibilityManager$Stub$Proxy.registerUiTestAutomationService(IAccessibilityManager.java:402)
        at android.app.UiAutomationConnection.registerUiTestAutomationServiceLocked(UiAutomationConnection.java:396)
        at android.app.UiAutomationConnection.connect(UiAutomationConnection.java:96)
        at android.app.UiAutomation.connect(UiAutomation.java:223)
        at android.app.UiAutomation.connect(UiAutomation.java:202)
        at com.android.commands.monkey.x.<init>(SourceFile:2265)
        at com.android.commands.monkey.Monkey.a(SourceFile:801)
        at com.android.commands.monkey.Monkey.main(SourceFile:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
[Fastbot][2022-01-17 12:30:28.471] Please report this bug issue to github

**Comment by yusandy0920** [comment]
重启手机后可正常执行
