### ISSUE TITLE
跑完monkey测试不出崩溃文件

### ISSUE THREAD

**Issue by shanksleo** [bytedance/Fastbot_Android#135]
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 6 column 56 path $.text
 at com.google.gson.Gson.fromJson(Gson.java:903)
 at com.google.gson.Gson.fromJson(Gson.java:853)
 at com.google.gson.Gson.fromJson(Gson.java:802)
 at com.google.gson.Gson.fromJson(Gson.java:774)
 at com.android.commands.monkey.fastbot.client.Operate.fromJson(SourceFile:54)
 at com.bytedance.fastbot.AiClient.l(SourceFile:1137)
 at com.android.commands.monkey.x.z(SourceFile:848)
 at com.android.commands.monkey.x.k(SourceFile:395)
 at com.android.commands.monkey.Monkey.f(SourceFile:1510)
 at com.android.commands.monkey.Monkey.a(SourceFile:867)
 at com.android.commands.monkey.Monkey.main(SourceFile:458)
 at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
 at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 6 column 56 path $.text
 at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
 at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
 at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:214)
 at com.google.gson.Gson.fromJson(Gson.java:888)
 ... 12 more

**Comment by geron-cn** [comment]
麻烦同时提供下对应的 logcat 呢

**Comment by shanksleo** [comment]
刚问了，不能直接提供出来文件，你这边可以提供下关键字么，我收集一点。 还有问下可能是什么方面的原因吗，我这边可以做点什么先规避

**Comment by geron-cn** [comment]
可以提供`adb shell logcat | grep "Fastbot"` 这部分即可。 或者看下当前页面是否有一些奇奇怪怪的编码的字符提供一下
