### ISSUE TITLE
monkey跑着跑着就出现at com.android.a.d.c.a(SourceFile:505)，打印了很多很多行，这是怎么了？

### ISSUE THREAD

**Issue by jeniva** [bytedance/Fastbot_Android#14]
at com.android.a.d.c.a(SourceFile:505)
        at com.android.a.d.c.a(SourceFile:505)
        at com.android.a.d.c.a(SourceFile:505)
        at com.android.a.d.c.a(SourceFile:505)
        at com.android.a.d.c.a(SourceFile:505)
        at com.android.a.d.c.a(SourceFile:505)
        at com.android.a.d.c.a(SourceFile:505)
        at com.android.a.d.c.a(SourceFile:505)
        at com.android.a.d.c.a(SourceFile:505)
        at com.android.a.d.c.<init>(SourceFile:1252)
        at com.android.a.c.j.b(SourceFile:107)
        at com.android.a.a.e.a(SourceFile:322)
        at com.android.a.a.e.c(SourceFile:2256)
        at com.android.a.a.b.b(SourceFile:236)
        at com.android.a.a.b.a(SourceFile:226)
        at com.android.commands.monkey.y.y(SourceFile:680)
        at com.android.commands.monkey.y.l(SourceFile:1239)
        at com.android.commands.monkey.Monkey.f(SourceFile:1861)
        at com.android.commands.monkey.Monkey.a(SourceFile:1105)
        at com.android.commands.monkey.Monkey.main(SourceFile:827)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
[1610003333759] Please report this bug issue to github

![image](https://user-images.githubusercontent.com/8514029/103863485-e7bf0100-50fb-11eb-8442-30e513004588.png)

**Comment by icexun** [comment]
遇到同样问题，补充下前面的log部分

[1610021630699] using nstep-q agent
[1610021630700] select new action from unvisited
[1610021630700] new state visited : 1
[1610021630700] new action visited : 0
[1610021630700] get new reward
[1610021630701] update Q value
[1610021630701] // previous State and action polled
[1610021630701] *** Making decisions *** 
[1610021630701] New  state: g7s26@com.baidu.homework.activity.init.InitActivity@1753926677
[1610021630702] New action: g7a366@CLICKWidget{hashCode=1037649737, index=0, clazz='android.widget.ImageView', resourceId='com.baidu.homework:id/adx_splash_container', operationTypeMask=6, scrollType=none, text='', contentDesc=''}[priority=24][throttle=200][][saturation=(0.0,1)][bounds=(0,0,1080,1920)]
[1610021630702] *** Inject event ***
[1610021630746]     // activityResuming(com.baidu.homework)
[1610021630969] : debug, currentActivity is com.baidu.homework.common.ad.VideoAndDownloadWebActivity
[1610021637552] // the top activity is com.android.systemui.recents.RecentsActivity, not testing app, need inject restart app
[1610021637552] fastbot exec shell: 
[1610021637567] fastbot exec schema: 
[1610021638005]     // activityResuming(com.baidu.homework)
[1610021644622] // Monkey is over!
[1610021644644] Running failed
java.lang.StackOverflowError: stack size 8MB
	at android.view.accessibility.AccessibilityNodeInfo.init(AccessibilityNodeInfo.java:3228)
	at android.view.accessibility.AccessibilityNodeInfo.obtain(AccessibilityNodeInfo.java:3017)
	at android.view.accessibility.AccessibilityCache.getNode(AccessibilityCache.java:228)
	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:318)
	at android.view.accessibility.AccessibilityNodeInfo.getChild(AccessibilityNodeInfo.java:965)
	at com.android.a.d.c.a(SourceFile:485)

**Comment by zhangzhao4444** [comment]
看log是oom了，该问题还在解决中

**Comment by zhangzhao4444** [comment]
与issus27问题一样，都是内存oom问题

**Comment by jeniva** [comment]
我换了最新的版本还是有出现呢
![image](https://user-images.githubusercontent.com/8514029/111407216-7c526a80-870e-11eb-806f-f95f42d70a4f.png)
