### ISSUE TITLE
运行的时候报 Error: Could not load library!

### ISSUE THREAD

**Issue by lwjcherry** [bytedance/Fastbot_Android#140]
[Fastbot][2022-02-25 18:34:57.637] // Eventid: 3
[Fastbot]*** ERROR *** Error: Could not load library!
java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/local/tmp/arm64-v8a/libfastbot_native.so" not found
        at java.lang.Runtime.load0(Runtime.java:939)
        at java.lang.System.load(System.java:1628)
        at com.bytedance.fastbot.AiClient.<clinit>(SourceFile:42)
        at com.bytedance.fastbot.AiClient.l(SourceFile:111)
        at com.android.commands.monkey.x.z(SourceFile:848)
        at com.android.commands.monkey.x.k(SourceFile:395)
        at com.android.commands.monkey.Monkey.f(SourceFile:1510)
        at com.android.commands.monkey.Monkey.a(SourceFile:867)
        at com.android.commands.monkey.Monkey.main(SourceFile:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:439)

**Comment by lwjcherry** [comment]
这个.so文件在libs里面有的

**Comment by buder-cp** [comment]
我也遇到了这个问题

**Comment by zhangzhao4444** [comment]
https://github.com/bytedance/Fastbot_Android/issues/138。几位同学参考下这个

**Comment by lwjcherry** [comment]
确实是目录层级的问题，已解决
