### ISSUE TITLE
实际上我放了 java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/local/tmp/arm64-v8a/libfastbot_native.so" not found

### ISSUE THREAD

**Issue by buder-cp** [bytedance/Fastbot_Android#148]
[Fastbot][2022-03-18 10:56:35.968] // phone info： HUAWEI_PCT-AL10_10
[Fastbot][2022-03-18 10:56:35.969] // runing fastbot
[Fastbot][2022-03-18 10:56:36.096] InputMethod ID: com.baidu.input_huawei/.ImeService
[Fastbot][2022-03-18 10:56:36.097] InputMethod ID: com.sohu.inputmethod.sogou/.SogouIME
[Fastbot][2022-03-18 10:56:36.101] // device serial number is 5EN0219228000473
[Fastbot][2022-03-18 10:56:36.122] // device uuid is 660ad1c1-85ca-48ab-8b22-430cd7cc4388
[Fastbot][2022-03-18 10:56:39.186] // init with reuse agent
[Fastbot]*** ERROR *** Error: Could not load library!
java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/local/tmp/arm64-v8a/libfastbot_native.so" not found
        at java.lang.Runtime.load0(Runtime.java:938)
        at java.lang.System.load(System.java:1632)
        at com.bytedance.fastbot.AiClient.<clinit>(SourceFile:42)
        at com.bytedance.fastbot.AiClient.a(SourceFile:73)
        at com.android.commands.monkey.x.r(SourceFile:331)
        at com.android.commands.monkey.Monkey.a(SourceFile:815)
        at com.android.commands.monkey.Monkey.main(SourceFile:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[Fastbot][2022-03-18 10:56:39.198] Internal error
java.lang.UnsatisfiedLinkError: No implementation found for void com.bytedance.fastbot.AiClient.fgdsaf5d(int, java.lang.String) (tried Java_com_bytedance_fastbot_AiClient_fgdsaf5d and Java_com_bytedance_fastbot_AiClient_fgdsaf5d__ILjava_lang_String_2)
        at com.bytedance.fastbot.AiClient.fgdsaf5d(Native Method)
        at com.bytedance.fastbot.AiClient.a(SourceFile:73)
        at com.android.commands.monkey.x.r(SourceFile:331)
        at com.android.commands.monkey.Monkey.a(SourceFile:815)
        at com.android.commands.monkey.Monkey.main(SourceFile:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[Fastbot][2022-03-18 10:56:39.203] Please report this bug issue to github

实际上我按照要求放置了所有的so到指定的目录。小米也会报这个错误

**Comment by buder-cp** [comment]
adb命令push时候，多了lib的文件夹导致。
