### ISSUE TITLE
小米和华为试了两台设备均报如下错误，so确实也放置到了指定目录

### ISSUE THREAD

**Issue by buder-cp** [bytedance/Fastbot_Android#149]
[Fastbot][2022-03-18 10:51:35.476] // phone info： Xiaomi_MI 8_10
[Fastbot][2022-03-18 10:51:35.476] // runing fastbot
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at java.io.FileReader.<init>(FileReader.java:58)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
        at android.content.res.Resources.<init>(Resources.java:285)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
        at android.content.res.Resources.getSystem(Resources.java:206)
        at android.app.ActivityManager.isHighEndGfx(ActivityManager.java:934)
        at android.app.ActivityThread.systemMain(ActivityThread.java:7357)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.commands.monkey.g.b.ao(SourceFile:46)
        at com.android.commands.monkey.framework.AndroidDevice.a(SourceFile:113)
        at com.android.commands.monkey.Monkey.a(SourceFile:794)
        at com.android.commands.monkey.Monkey.main(SourceFile:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        ... 21 more
[Fastbot][2022-03-18 10:51:35.514] InputMethod ID: com.sohu.inputmethod.sogou.xiaomi/.SogouIME
[Fastbot][2022-03-18 10:51:35.517] // device serial number is 4d00b597
[Fastbot][2022-03-18 10:51:35.535] // device uuid is b724a402-9672-43d0-94f2-3582e520be66
[Fastbot][2022-03-18 10:51:44.115] // init with reuse agent
[Fastbot]*** ERROR *** Error: Could not load library!
java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/local/tmp/arm64-v8a/libfastbot_native.so" not found
        at java.lang.Runtime.load0(Runtime.java:938)
        at java.lang.System.load(System.java:1631)
        at com.bytedance.fastbot.AiClient.<clinit>(SourceFile:42)
        at com.bytedance.fastbot.AiClient.a(SourceFile:73)
        at com.android.commands.monkey.x.r(SourceFile:331)
        at com.android.commands.monkey.Monkey.a(SourceFile:815)
        at com.android.commands.monkey.Monkey.main(SourceFile:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
[Fastbot][2022-03-18 10:51:44.131] Internal error
java.lang.UnsatisfiedLinkError: No implementation found for void com.bytedance.fastbot.AiClient.fgdsaf5d(int, java.lang.String) (tried Java_com_bytedance_fastbot_AiClient_fgdsaf5d and Java_com_bytedance_fastbot_AiClient_fgdsaf5d__ILjava_lang_String_2)
        at com.bytedance.fastbot.AiClient.fgdsaf5d(Native Method)
        at com.bytedance.fastbot.AiClient.a(SourceFile:73)
        at com.android.commands.monkey.x.r(SourceFile:331)
        at com.android.commands.monkey.Monkey.a(SourceFile:815)
        at com.android.commands.monkey.Monkey.main(SourceFile:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
[Fastbot][2022-03-18 10:51:44.134] Please report this bug issue to github

同问题 https://github.com/bytedance/Fastbot_Android/issues/107

**Comment by buder-cp** [comment]
adb命令push时候，多了lib的文件夹导致。

对比下错误日志，看下自己目录是不是错了

**Comment by buder-cp** [comment]
adb命令push时候，多了lib的文件夹导致。

对比下错误日志，看下自己目录是不是错了
