### ISSUE TITLE
启动的时候出现了 AccessBility 的错误

### ISSUE THREAD

**Issue by Kim-LL** [bytedance/Fastbot_Android#152]
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@d62a20ealready registered!
	at android.os.Parcel.readException(Parcel.java:1959)
	at android.os.Parcel.readException(Parcel.java:1897)
	at android.view.accessibility.IAccessibilityManager$Stub$Proxy.registerUiTestAutomationService(IAccessibilityManager.java:402)
	at android.app.UiAutomationConnection.registerUiTestAutomationServiceLocked(UiAutomationConnection.java:344)
	at android.app.UiAutomationConnection.connect(UiAutomationConnection.java:92)
	at android.app.UiAutomation.connect(UiAutomation.java:223)
	at android.app.UiAutomation.connect(UiAutomation.java:202)
	at com.android.commands.monkey.x.<init>(SourceFile:2265)
	at com.android.commands.monkey.Monkey.a(SourceFile:801)
	at com.android.commands.monkey.Monkey.main(SourceFile:458)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:284)

**Comment by Kim-LL** [comment]
重新拔插手机就好了

**Comment by Kim-LL** [comment]
原来是当前运行的机器开了一个页面监控，两个程序冲突了！
