### ISSUE TITLE
运行时出现"/data/local/tmp/arm64-v8a/libfastbot_native.so" not found怎么解决？已经执行过adb push libs/* /data/local/tmp/

### ISSUE THREAD

**Issue by tang-wangyisuifeng** [bytedance/Fastbot_Android#155]
java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/local/tmp/arm64-v8a/libfastbot_native.so" not found
        at java.lang.Runtime.load0(Runtime.java:928)
        at java.lang.System.load(System.java:1621)
        at com.bytedance.fastbot.AiClient.<clinit>(SourceFile:42)
        at com.bytedance.fastbot.AiClient.a(SourceFile:73)
        at com.android.commands.monkey.x.r(SourceFile:331)
        at com.android.commands.monkey.Monkey.a(SourceFile:815)
        at com.android.commands.monkey.Monkey.main(SourceFile:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)
[Fastbot][2022-04-07 13:00:14.892] Internal error
java.lang.UnsatisfiedLinkError: No implementation found for void com.bytedance.fastbot.AiClient.fgdsaf5d(int, java.lang.String) (tried Java_com_bytedance_fastbot_AiClient_fgdsaf5d and Java_com_bytedance_fastbot_AiClient_fgdsaf5d__ILjava_lang_String_2)
        at com.bytedance.fastbot.AiClient.fgdsaf5d(Native Method)
        at com.bytedance.fastbot.AiClient.a(SourceFile:73)
        at com.android.commands.monkey.x.r(SourceFile:331)
        at com.android.commands.monkey.Monkey.a(SourceFile:815)
        at com.android.commands.monkey.Monkey.main(SourceFile:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)

/data这目录手机没有权限打开的

**Comment by tang-wangyisuifeng** [comment]
求助

**Comment by tang-wangyisuifeng** [comment]
已经解决了

**Comment by gavin-huangwang** [comment]
> 已经解决了

怎么解决的？

**Comment by geron-cn** [comment]
> 

运行 `adb shell ls -l  /data/local/tmp/arm64-v8a/libfastbot_native.so ` 确认下文件是否存在
