### ISSUE TITLE
【Bug】三星S21Ultra（Android12）运行5小时左右失败

### ISSUE THREAD

**Issue by ZhangJiaDi091** [bytedance/Fastbot_Android#161]
[1650822361210] Running failed
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 1592328 free bytes and 1555KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at com.android.a.e.o.println(SourceFile:38)
	at com.android.a.a.e.c(SourceFile:2261)
	at com.android.a.a.b.b(SourceFile:236)
	at com.android.a.a.b.a(SourceFile:226)
	at com.android.commands.monkey.y.y(SourceFile:680)
	at com.android.commands.monkey.y.l(SourceFile:1239)
	at com.android.commands.monkey.Monkey.f(SourceFile:1861)
	at com.android.commands.monkey.Monkey.a(SourceFile:1105)
	at com.android.commands.monkey.Monkey.main(SourceFile:827)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:374)
[1650822361211] Please report this bug issue to github

**Comment by geron-cn** [comment]
可更新到最新版本已经修复了这个问题； （注意查看 readme 新版包和启动命令有更新）
