### ISSUE TITLE
Google Pixel 2XL（Android11）运行4小时左右报错

### ISSUE THREAD

**Issue by ZhangJiaDi091** [bytedance/Fastbot_Android#162]
[1650818572687] Running failed
java.lang.OutOfMemoryError: Failed to allocate a 31448 byte allocation with 11592 free bytes and 11KB until OOM, target footprint 201326592, growth limit 201326592
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
	at java.lang.StringBuffer.toString(StringBuffer.java:671)
	at java.io.StringWriter.toString(StringWriter.java:210)
	at com.android.a.d.a.bZ(SourceFile:170)
	at com.android.a.a.e.c(SourceFile:2261)
	at com.android.a.a.b.b(SourceFile:236)
	at com.android.a.a.b.a(SourceFile:226)
	at com.android.commands.monkey.y.y(SourceFile:680)
	at com.android.commands.monkey.y.l(SourceFile:1239)
	at com.android.commands.monkey.Monkey.f(SourceFile:1861)
	at com.android.commands.monkey.Monkey.a(SourceFile:1105)
	at com.android.commands.monkey.Monkey.main(SourceFile:827)
[1650818573377] 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
Please report this bug issue to github

**Comment by geron-cn** [comment]
> related #161
