### ISSUE TITLE
Could not load library!

### ISSUE THREAD

**Issue by Bigmom007** [bytedance/Fastbot_Android#168]
[Fastbot][2022-06-02 18:38:07.255] // phone info： OnePlus_GM1910_11
[Fastbot][2022-06-02 18:38:07.256] // runing fastbot
[Fastbot][2022-06-02 18:38:07.314] InputMethod ID: com.baidu.input_yijia/.ImeService
[Fastbot][2022-06-02 18:38:07.315] InputMethod ID: io.appium.settings/.UnicodeIME
[Fastbot][2022-06-02 18:38:07.319] // device serial number is 80d5851d
[Fastbot][2022-06-02 18:38:07.352] // device uuid is e95a6c67-c18c-4016-a2ef-9ccff85d8cde
[Fastbot][2022-06-02 18:38:10.242] // init with reuse agent
[Fastbot]*** ERROR *** Error: Could not load library!
java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/local/tmp/arm64-v8a/libfastbot_native.so" not found
        at java.lang.Runtime.load0(Runtime.java:939)
        at java.lang.System.load(System.java:1628)
        at com.bytedance.fastbot.AiClient.<clinit>(SourceFile:42)
        at com.bytedance.fastbot.AiClient.a(SourceFile:73)
        at com.android.commands.monkey.x.r(SourceFile:331)
        at com.android.commands.monkey.Monkey.a(SourceFile:815)
        at com.android.commands.monkey.Monkey.main(SourceFile:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:438)
[Fastbot][2022-06-02 18:38:10.253] Internal error
java.lang.UnsatisfiedLinkError: No implementation found for void com.bytedance.fastbot.AiClient.fgdsaf5d(int, java.lang.String) (tried Java_com_bytedance_fastbot_AiClient_fgdsaf5d and Java_com_bytedance_fastbot_AiClient_fgdsaf5d__ILjava_lang_String_2)
        at com.bytedance.fastbot.AiClient.fgdsaf5d(Native Method)
        at com.bytedance.fastbot.AiClient.a(SourceFile:73)
        at com.android.commands.monkey.x.r(SourceFile:331)
        at com.android.commands.monkey.Monkey.a(SourceFile:815)
        at com.android.commands.monkey.Monkey.main(SourceFile:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:438)
[Fastbot][2022-06-02 18:38:10.256] Please report this bug issue to github

**Comment by Bigmom007** [comment]
不好意思，找到问题了，我没找到在哪删除这个issue

**Comment by astrid77** [comment]
> 不好意思，找到问题了，我没找到在哪删除这个issue

我也遇到这个问题，请问是怎么解决的啊？

**Comment by Bigmom007** [comment]
> > 不好意思，找到问题了，我没找到在哪删除这个issue
> 
> 我也遇到这个问题，请问是怎么解决的啊？

adb shell 看下/data/local/tmp/下是不是把libs目录也复制进来了，libs里边是要复制的那几个文件，把这几个文件从libs里拉出来放到tmp目录下

**Comment by Bigmom007** [comment]
> > 不好意思，找到问题了，我没找到在哪删除这个issue
> 
> 我也遇到这个问题，请问是怎么解决的啊？

![image](https://user-images.githubusercontent.com/22930118/171624767-4e69560a-8e4d-4e67-a2f7-1c38661b8509.png)
要复制的是这几个文件到tmp里，不复制libs文件夹

**Comment by astrid77** [comment]
> > > 不好意思，找到问题了，我没找到在哪删除这个issue
> > 
> > 
> > 我也遇到这个问题，请问是怎么解决的啊？
> 
> ![image](https://user-images.githubusercontent.com/22930118/171624767-4e69560a-8e4d-4e67-a2f7-1c38661b8509.png) 要复制的是这几个文件到tmp里，不复制libs文件夹

感谢，已解决~
