### ISSUE TITLE
登录操作时出现DeadSystemException错误

### ISSUE THREAD

**Issue by seminchen** [bytedance/Fastbot_Android#178]
[1657853100742] // Monkey is over!
[1657853100742] :Sending rotation degree : 0, persist : false
[1657853100742] Running failed
java.lang.RuntimeException: android.os.DeadSystemException
        at android.app.ActivityManager.getCurrentUser(ActivityManager.java:4036)
        at com.android.commands.monkey.f.a(SourceFile:82)
        at com.android.commands.monkey.Monkey.f(SourceFile:1863)
        at com.android.commands.monkey.Monkey.a(SourceFile:1105)
        at com.android.commands.monkey.Monkey.main(SourceFile:827)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Caused by: android.os.DeadSystemException
        ... 7 more
[1657853100743] Please report this bug issue to github
请按任意键继续. . .

**Comment by zhangzhao4444** [comment]
已知偶见问题，底层系统异常会报这个error，这种情况需要重启设备
