### ISSUE TITLE
java.lang.ClassNotFoundException: com.google.gson.GsonBuilder

### ISSUE THREAD

**Issue by linke1** [bytedance/Fastbot_Android#180]
下载的jar包大小一致，按照文档将3个jar包放入了sdcard下，执行命令时报错如下：
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/GsonBuilder;
	at com.android.commands.monkey.fastbot.client.GsonIface.<clinit>(SourceFile:28)
	at com.android.commands.monkey.fastbot.client.Operate.fromJson(SourceFile:54)
	at com.bytedance.fastbot.AiClient.l(SourceFile:1137)
	at com.android.commands.monkey.x.I(SourceFile:849)
	at com.android.commands.monkey.x.l(SourceFile:396)
	at com.android.commands.monkey.Monkey.f(SourceFile:1510)
	at com.android.commands.monkey.Monkey.a(SourceFile:867)
	at com.android.commands.monkey.Monkey.main(SourceFile:458)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder

**Comment by Zhang-aijw817** [comment]
你好，我也遇到了这个问题，可能是参数配置不完整（我遗漏了fastbot-thirdpart.jard的路径)adb -s device_vendor_id shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar:/sdcard/fastbot-thirdpart.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p package_name --agent reuseq --running-minutes duration(min) --throttle delay(ms) -v -v

**Comment by Zhang-aijw817** [comment]
你好，我也遇到了这个问题，我出问题的原因是：参数配置不完整（我遗漏了fastbot-thirdpart.jar的路径)，复制作者提供的运行命令后解决。

**Comment by zhangzhao4444** [comment]
嗯 如上所述
