### ISSUE TITLE
报错java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/GsonBuilder;

### ISSUE THREAD

**Issue by wjm12345** [bytedance/Fastbot_Android#186]
[Fastbot][2022-08-17 19:47:38.036] // current activity is com.android.browser.BrowserActivity
[Fastbot][2022-08-17 19:47:38.038] Sleeping for 2000 milliseconds
[Fastbot][2022-08-17 19:47:40.062] // Eventid: 3
[Fastbot][2022-08-17 19:47:40.081] fastbot native : library load!
[Fastbot][2022-08-17 19:47:40.087] // Monkey is over!
[Fastbot][2022-08-17 19:47:40.088] :Sending rotation degree=0, persist=false
[Fastbot][2022-08-17 19:47:40.107] Internal error
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/GsonBuilder;
        at com.android.commands.monkey.fastbot.client.GsonIface.<clinit>(SourceFile:28)
        at com.android.commands.monkey.fastbot.client.Operate.fromJson(SourceFile:54)
        at com.bytedance.fastbot.AiClient.l(SourceFile:1137)
        at com.android.commands.monkey.x.I(SourceFile:849)
        at com.android.commands.monkey.x.l(SourceFile:396)
        at com.android.commands.monkey.Monkey.f(SourceFile:1510)
        at com.android.commands.monkey.Monkey.a(SourceFile:867)
        at com.android.commands.monkey.Monkey.main(SourceFile:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:391)
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
        ... 10 more
[Fastbot][2022-08-17 19:47:40.109] Please report this bug issue to github

**Comment by geron-cn** [comment]
> related #121  参照 readme 注意 push 那个 thirdpart.jar ，然后执行命令中 classpath 也需要存在此 jar
