### ISSUE TITLE
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@a3206eaalready registered!

### ISSUE THREAD

**Issue by sweeeeeet** [bytedance/Fastbot_Android#187]
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@a3206eaalready registered!
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2433)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.view.accessibility.IAccessibilityManager$Stub$Proxy.registerUiTestAutomationService(IAccessibilityManager.java:830)
	at android.app.UiAutomationConnection.registerUiTestAutomationServiceLocked(UiAutomationConnection.java:532)
	at android.app.UiAutomationConnection.connect(UiAutomationConnection.java:109)
	at android.app.UiAutomation.connectWithTimeout(UiAutomation.java:324)
	at android.app.UiAutomation.connect(UiAutomation.java:276)
	at com.android.commands.monkey.x.<init>(SourceFile:2266)
	at com.android.commands.monkey.Monkey.a(SourceFile:801)
	at com.android.commands.monkey.Monkey.main(SourceFile:458)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.accessibility.UiAutomationManager.registerUiTestAutomationServiceLocked(UiAutomationManager.java:102)
	at com.android.server.accessibility.AccessibilityManagerService.registerUiTestAutomationService(AccessibilityManagerService.java:1039)
	at android.view.accessibility.IAccessibilityManager$Stub.onTransact(IAccessibilityManager.java:404)
	at android.os.Binder.execTransactInternal(Binder.java:1182)
	at android.os.Binder.execTransact(Binder.java:1146)

**Comment by Secret111baby** [comment]
hello，请问问题解决了 吗

**Comment by zhangzhao4444** [comment]
这个非问题，fastbot跑的过程中其他自动化框架不能同时运行

**Comment by zhangzhao4444** [comment]
可以参考下 q&a
