### ISSUE TITLE
[crash] Fastbot默认测试过程中monkey崩溃

### ISSUE THREAD

**Issue by NasdaqGodzilla** [bytedance/Fastbot_Android#194]
```
Fastbot running...
java.lang.IllegalArgumentException: bound must be positive
        at java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:297)
        at com.android.commands.monkey.g.m.k(SourceFile:57)
        at com.android.commands.monkey.b.i.a(SourceFile:354)
        at com.android.commands.monkey.b.i.b(SourceFile:403)
        at com.android.commands.monkey.b.i.k(SourceFile:45)
        at com.android.commands.monkey.b.v.a(SourceFile:230)
        at com.android.commands.monkey.b.i.an(SourceFile:310)
        at com.android.commands.monkey.x.c(SourceFile:1003)
        at com.android.commands.monkey.x.l(SourceFile:3430)
        at com.android.commands.monkey.Monkey.f(SourceFile:1510)
        at com.android.commands.monkey.Monkey.a(SourceFile:867)
        at com.android.commands.monkey.Monkey.main(SourceFile:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:412)
```

Android 11；被测应用处于窗口模式下运行

**Comment by zhangzhao4444** [comment]
hi 同学请加下qq

**Comment by zhangzhao4444** [comment]
77227005

**Comment by NasdaqGodzilla** [comment]
See https://github.com/bytedance/Fastbot_Android/issues/193
