### ISSUE TITLE
【Crash】【必现】Xiaomi_M2007J20CG_10 设备执行过程中发生Crash

### ISSUE THREAD

**Issue by chaoyuebaihu** [bytedance/Fastbot_Android#195]
[Fastbot][2022-10-21 17:38:09.856] // crash processName: com.android.se, is not testing app
[Fastbot][2022-10-21 17:38:10.653] // phone info： Xiaomi_M2007J20CG_10
[Fastbot][2022-10-21 17:38:10.653] // runing fastbot
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at java.io.FileReader.<init>(FileReader.java:58)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
        at android.content.res.Resources.<init>(Resources.java:285)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
        at android.content.res.Resources.getSystem(Resources.java:206)
        at android.app.ActivityManager.isHighEndGfx(ActivityManager.java:936)
        at android.app.ActivityThread.systemMain(ActivityThread.java:7360)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.commands.monkey.g.b.aC(SourceFile:46)
        at com.android.commands.monkey.framework.AndroidDevice.a(SourceFile:114)
        at com.android.commands.monkey.Monkey.a(SourceFile:794)
        at com.android.commands.monkey.Monkey.main(SourceFile:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        ... 21 more

**Comment by zhangzhao4444** [comment]
/data/system/theme_config/theme_compatibility.xml: open failed: ENOENT 这个error 并不影响fastbot运行
