### ISSUE TITLE
运行过程中报错

### ISSUE THREAD

**Issue by wjm12345** [bytedance/Fastbot_Android#203]
[Fastbot][2022-11-28 20:37:30.584] Internal error
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@d2c2ac1already registered!
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2450)
	at android.os.Parcel.createException(Parcel.java:2426)
	at android.os.Parcel.readException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2351)
	at android.view.accessibility.IAccessibilityManager$Stub$Proxy.registerUiTestAutomationService(IAccessibilityManager.java:830)
	at android.app.UiAutomationConnection.registerUiTestAutomationServiceLocked(UiAutomationConnection.java:532)
	at android.app.UiAutomationConnection.connect(UiAutomationConnection.java:109)
	at android.app.UiAutomation.connectWithTimeout(UiAutomation.java:324)
	at android.app.UiAutomation.connect(UiAutomation.java:276)
	at com.android.commands.monkey.x.(SourceFile:2266)
	at com.android.commands.monkey.Monkey.a(SourceFile:801)
	at com.android.commands.monkey.Monkey.main(SourceFile:458)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:391)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.accessibility.UiAutomationManager.registerUiTestAutomationServiceLocked(UiAutomationManager.java:102)
	at com.android.server.accessibility.AccessibilityManagerService.registerUiTestAutomationService(AccessibilityManagerService.java:1045)
	at android.view.accessibility.IAccessibilityManager$Stub.onTransact(IAccessibilityManager.java:404)
	at android.os.Binder.execTransactInternal(Binder.java:1221)
	at android.os.Binder.execTransact(Binder.java:1163)

[Fastbot][2022-11-28 20:37:30.585] Please report this bug issue to github

**Comment by lixf6** [comment]
同样报错

**Comment by zhangzhao4444** [comment]
请参考手册中QA部分，运行 Fastbot 同时不能再运行其他自动化框架
