### ISSUE TITLE
启动时异常报错

### ISSUE THREAD

**Issue by wjm12345** [bytedance/Fastbot_Android#204]
2022-11-30 11:49:48.507 [ CCTAutoPlugin ] [ ERROR ]：2022-11-30 11:49:48.497 exec shell command failed : null
2022-11-30 11:49:48.507 [ CCTAutoPlugin ] [ ERROR ]：com.android.ddmlib.ShellCommandUnresponsiveException
2022-11-30 11:49:48.508 [ CCTAutoPlugin ] [ ERROR ]：	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:548)
2022-11-30 11:49:48.508 [ CCTAutoPlugin ] [ ERROR ]：	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:417)

**Comment by zhangzhao4444** [comment]
这个不是fastbot打印的log
