### ISSUE TITLE
LG Stylo4 设备启动 fastbot 报 ExceptionInInitializerError 异常

### ISSUE THREAD

**Issue by Kim-LL** [bytedance/Fastbot_Android#206]
设备: LG Stylo 4
系统: 8.1.0
语言: 中文 & 英文

错误日志:
java.lang.ExceptionInInitializerError
	at com.lge.systemservice.core.LGContext.<clinit>(LGContext.java:409)
	at android.app.ApplicationPackageManager.getLGPackageLabelService(ApplicationPackageManager.java:1763)
	at android.app.ApplicationPackageManager.<init>(ApplicationPackageManager.java:1505)
	at android.app.ContextImpl.getPackageManager(ContextImpl.java:237)
	at com.android.commands.monkey.framework.AndroidDevice.a(SourceFile:115)
	at com.android.commands.monkey.Monkey.a(SourceFile:794)
	at com.android.commands.monkey.Monkey.main(SourceFile:458)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x60044
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:231)
	at android.content.res.Resources.getBoolean(Resources.java:1066)
	at com.lge.systemservice.core.LGMiniClockManager.<clinit>(LGMiniClockManager.java:23)
	... 9 more

**Comment by Kim-LL** [comment]
没有人解决这个问题吗？

**Comment by Kim-LL** [comment]
继续发，这个问题没有办法解决了

[Fastbot][2023-02-17 16:50:09.928]  @Version: 2.2.02.0708.1723-git
[Fastbot][2023-02-17 16:50:09.950] // Monkey: seed=1676746090332 count=1000


[Fastbot][2023-02-17 16:50:09.951] // AllowPackage: com.plusme.live
[Fastbot][2023-02-17 16:50:09.952] // IncludeCategory: android.intent.category.LAUNCHER
[Fastbot][2023-02-17 16:50:09.952] // IncludeCategory: android.intent.category.MONKEY
[Fastbot][2023-02-17 16:50:10.049] // Selecting main activities from category android.intent.category.LAUNCHER
[Fastbot][2023-02-17 16:50:10.051] //   - NOT USING main activity com.google.android.apps.chrome.Main (from package com.android.chrome)
[Fastbot][2023-02-17 16:50:10.052] //   - NOT USING main activity com.android.contacts.activities.PeopleActivity (from package com.android.contacts)
[Fastbot][2023-02-17 16:50:10.053] //   - NOT USING main activity com.android.contacts.activities.DialtactsActivity (from package com.android.contacts)
[Fastbot][2023-02-17 16:50:10.054] //   - NOT USING main activity com.android.gallery3d.app.Gallery (from package com.android.gallery3d)
[Fastbot][2023-02-17 16:50:10.055] //   - NOT USING main activity com.android.mms.ui.ConversationList (from package com.android.mms)
[Fastbot][2023-02-17 16:50:10.056] //   - NOT USING main activity com.android.settings.Settings (from package com.android.settings)
[Fastbot][2023-02-17 16:50:10.057] //   - NOT USING main activity com.android.vending.AssetBrowserActivity (from package com.android.vending)
[Fastbot][2023-02-17 16:50:10.058] //   - NOT USING main activity com.google.android.apps.docs.app.NewMainProxyActivity (from package com.google.android.apps.docs)
[Fastbot][2023-02-17 16:50:10.059] //   - NOT USING main activity com.google.android.apps.docs.app.NewMainProxyActivity (from package com.google.android.apps.docs.editors.docs)
[Fastbot][2023-02-17 16:50:10.060] //   - NOT USING main activity com.google.android.apps.docs.app.NewMainProxyActivity (from package com.google.android.apps.docs.editors.slides)
[Fastbot][2023-02-17 16:50:10.060] //   - NOT USING main activity com.google.android.maps.MapsActivity (from package com.google.android.apps.maps)
[Fastbot][2023-02-17 16:50:10.061] //   - NOT USING main activity com.google.android.apps.photos.home.HomeActivity (from package com.google.android.apps.photos)
[Fastbot][2023-02-17 16:50:10.062] //   - NOT USING main activity com.google.android.apps.tachyon.MainActivity (from package com.google.android.apps.tachyon)
[Fastbot][2023-02-17 16:50:10.063] //   - NOT USING main activity com.android.calendar.AllInOneActivity (from package com.google.android.calendar)
[Fastbot][2023-02-17 16:50:10.064] //   - NOT USING main activity com.google.android.gm.ConversationListActivityGmail (from package com.google.android.gm)
[Fastbot][2023-02-17 16:50:10.066] //   - NOT USING main activity com.android.music.activitymanagement.TopLevelActivity (from package com.google.android.music)
[Fastbot][2023-02-17 16:50:10.066] //   - NOT USING main activity com.google.android.youtube.app.honeycomb.Shell$HomeActivity (from package com.google.android.youtube)
[Fastbot][2023-02-17 16:50:10.067] //   - NOT USING main activity com.lge.camera.CameraAppLauncher (from package com.lge.camera)
[Fastbot][2023-02-17 16:50:10.068] //   - NOT USING main activity com.lge.hifirecorder.LaunchHifiRecorder (from package com.lge.hifirecorder)
[Fastbot][2023-02-17 16:50:10.069] //   - NOT USING main activity com.lge.hotspotlauncher.HotspotLauncher (from package com.lge.hotspotlauncher)
[Fastbot][2023-02-17 16:50:10.069] //   - NOT USING main activity com.lge.music.MusicBrowserActivity (from package com.lge.music)
[Fastbot][2023-02-17 16:50:10.070] //   - NOT USING main activity com.lookout.ui.LoadDispatch (from package com.lookout)
[Fastbot][2023-02-17 16:50:10.071] //   - NOT USING main activity com.amazon.aa.LodestarLauncherActivity (from package com.amazon.aa)
[Fastbot][2023-02-17 16:50:10.071] //   - NOT USING main activity com.android.documentsui.LauncherActivity (from package com.android.documentsui)
[Fastbot][2023-02-17 16:50:10.072] //   - NOT USING main activity com.google.android.apps.subscriptions.red.LauncherActivity (from package com.google.android.apps.subscriptions.red)
[Fastbot][2023-02-17 16:50:10.073] //   - NOT USING main activity com.android.calculator2.Calculator (from package com.google.android.calculator)
[Fastbot][2023-02-17 16:50:10.073] //   - NOT USING main activity com.google.android.googlequicksearchbox.SearchActivity (from package com.google.android.googlequicksearchbox)
[Fastbot][2023-02-17 16:50:10.074] //   - NOT USING main activity com.handmark.metro.launcher.Launcher (from package com.handmark.metro.launcher)
[Fastbot][2023-02-17 16:50:10.075] //   - NOT USING main activity com.lge.bnr.launcher.BNRLauncherActivity (from package com.lge.bnr.launcher)
[Fastbot][2023-02-17 16:50:10.076] //   - NOT USING main activity com.lge.clock.AlarmClockActivity (from package com.lge.clock)
[Fastbot][2023-02-17 16:50:10.077] //   - NOT USING main activity com.lge.email.ui.setupwizard.Welcome (from package com.lge.email)
[Fastbot][2023-02-17 16:50:10.078] //   - NOT USING main activity com.lge.filemanager.view.LaunchActivity (from package com.lge.filemanager)
[Fastbot][2023-02-17 16:50:10.079] //   - NOT USING main activity com.lge.fmradio.IntroActivity (from package com.lge.fmradio)
[Fastbot][2023-02-17 16:50:10.080] //   - NOT USING main activity com.lge.lgworld.ui.activity.MainActivity (from package com.lge.lgworld)
[Fastbot][2023-02-17 16:50:10.081] //   - NOT USING main activity com.lge.phonemanagement.ui.MainActivity (from package com.lge.phonemanagement)
[Fastbot][2023-02-17 16:50:10.082] //   - NOT USING main activity com.lge.qmemoplus.ui.main.MainActivity (from package com.lge.qmemoplus)
[Fastbot][2023-02-17 16:50:10.082] //   - NOT USING main activity com.lge.updatecenter.UpdateCenterPrfActivity (from package com.lge.updatecenter)
[Fastbot][2023-02-17 16:50:10.083] //   - NOT USING main activity com.metro.simlock.WelcomeActivity (from package com.metro.simlock)
[Fastbot][2023-02-17 16:50:10.084] //   - NOT USING main activity com.mobileposse.client.mp5.lib.view.screen.ControllerActivity (from package com.metropcs.metrozone)
[Fastbot][2023-02-17 16:50:10.085] //   - NOT USING main activity com.nuance.nmc.sihome.metropcs.myMetro (from package com.nuance.nmc.sihome.metropcs)
[Fastbot][2023-02-17 16:50:10.086] //   - NOT USING main activity com.privacystar.core.ui.EulaActivity (from package com.privacystar.android.metro)
[Fastbot][2023-02-17 16:50:10.087] //   - NOT USING main activity com.auto.helper.activity.MainActivity (from package com.auto.helper)
[Fastbot][2023-02-17 16:50:10.088] //   + Using main activity com.app.live.normal (from package com.plusme.live)
[Fastbot][2023-02-17 16:50:10.095] // Selecting main activities from category android.intent.category.MONKEY
[Fastbot][2023-02-17 16:50:10.096] //   - NOT USING main activity com.android.settings.Settings$RunningServicesActivity (from package com.android.settings)
[Fastbot][2023-02-17 16:50:10.097] //   - NOT USING main activity com.android.settings.Settings$StorageUseActivity (from package com.android.settings)
[Fastbot][2023-02-17 16:50:10.098] //   - NOT USING main activity com.android.settingsaccessibility.SettingsAccessibilityActivity (from package com.android.settingsaccessibility)
[Fastbot][2023-02-17 16:50:10.099] //   - NOT USING main activity com.lge.NfcSettings.MainActivity (from package com.lge.NfcSettings)
[Fastbot][2023-02-17 16:50:10.099] //   - NOT USING main activity com.lge.bluetoothsetting.LGBluetoothSettingActivity (from package com.lge.bluetoothsetting)
[Fastbot][2023-02-17 16:50:10.100] //   - NOT USING main activity com.lge.launcher3.EasyHomeLauncherExtension (from package com.lge.launcher3)
[Fastbot][2023-02-17 16:50:10.101] //   - NOT USING main activity com.lge.launcher3.LauncherExtension (from package com.lge.launcher3)
[Fastbot][2023-02-17 16:50:10.102] //   - NOT USING main activity com.lge.launcher3.AllAppsLauncherExtension (from package com.lge.launcher3)
[Fastbot][2023-02-17 16:50:10.103] //   - NOT USING main activity com.lge.phonemanagement.ui.SmartDoctorActivity (from package com.lge.phonemanagement)
[Fastbot][2023-02-17 16:50:10.104] //   - NOT USING main activity com.lge.wifisettings.activity.WifiSettingsActivity (from package com.lge.wifisettings)
[Fastbot][2023-02-17 16:50:10.105] //   - NOT USING main activity com.google.android.googlequicksearchbox.SearchActivity (from package com.google.android.googlequicksearchbox)
[Fastbot][2023-02-17 16:50:10.106] //   - NOT USING main activity com.lge.appbox.client.AppBoxClient (from package com.lge.appbox.client)
[Fastbot][2023-02-17 16:50:13.110] // phone info： LGE_LM-Q710(FGN)_8.1.0
[Fastbot][2023-02-17 16:50:13.111] // runing fastbot
[Fastbot][2023-02-17 16:50:13.141] Internal error
[Fastbot][2023-02-17 16:50:13.146] Please report this bug issue to github

**Comment by zhangzhao4444** [comment]
收到，抽空排查下，这个问题之前没遇到过
