### ISSUE TITLE
关于内存

### ISSUE THREAD

**Issue by zhl77015223** [bytedance/Fastbot_Android#21]
[1610651139970] *** Get guitree ***
[1610651144025] // Monkey is over!
[1610651144025] :Sending rotation degree : 0, persist : false
[1610651144080] Running failed
java.lang.OutOfMemoryError: Failed to allocate a 9108 byte allocation with 6544112 free bytes and 6MB until OOM; failed due to fragmentation (required continguous free 12288 bytes where largest contiguous free 8192 bytes)
        at java.lang.StringFactory.newStringFromChars(Native Method)
        at java.lang.AbstractStringBuilder.toString(AbstractStringBuilder.java:629)
        at java.lang.StringBuffer.toString(StringBuffer.java:723)
        at java.io.StringWriter.toString(StringWriter.java:100)
        at com.android.a.d.a.bZ(SourceFile:170)
        at com.android.a.a.e.c(SourceFile:2261)
        at com.android.a.a.b.b(SourceFile:236)
        at com.android.a.a.b.a(SourceFile:226)
        at com.android.commands.monkey.y.y(SourceFile:680)
        at com.android.commands.monkey.y.l(SourceFile:1239)
        at com.android.commands.monkey.Monkey.f(SourceFile:1861)
        at com.android.commands.monkey.Monkey.a(SourceFile:1105)
        at com.android.commands.monkey.Monkey.main(SourceFile:827)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
[1610651144081] Please report this bug issue to github

**Comment by zhangzhao4444** [comment]
已知问题，已有相关issue
