### ISSUE TITLE
测试过程中抛出异常导致直接结束，总是跑不到想要的时间，怎么处理

### ISSUE THREAD

**Issue by hatusyoki** [bytedance/Fastbot_Android#213]
[Fastbot]*** ERROR *** Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference
java.lang.NullPointerException: Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference
        at android.os.Parcel.createException(Parcel.java:1956)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.accessibilityservice.IAccessibilityServiceConnection$Stub$Proxy.findAccessibilityNodeInfoByAccessibilityId(IAccessibilityServiceConnection.java:451)
        at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:343)
        at android.view.accessibility.AccessibilityInteractionClient.getRootInActiveWindow(AccessibilityInteractionClient.java:207)
        at android.app.UiAutomation.getRootInActiveWindow(UiAutomation.java:495)
        at com.android.commands.monkey.x.I(SourceFile:12341)
        at com.android.commands.monkey.x.l(SourceFile:396)
        at com.android.commands.monkey.Monkey.f(SourceFile:1510)
        at com.android.commands.monkey.Monkey.a(SourceFile:867)
        at com.android.commands.monkey.Monkey.main(SourceFile:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:361)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.appwidget.AppWidgetServiceImpl$AppWidgetManagerLocal.getHostedWidgetPackages(AppWidgetServiceImpl.java:4802)
        at com.android.server.accessibility.AccessibilityManagerService$SecurityPolicy.computeValidReportedPackages(AccessibilityManagerService.java:3058)
        at com.android.server.accessibility.AbstractAccessibilityServiceConnection.findAccessibilityNodeInfoByAccessibilityId(AbstractAccessibilityServiceConnection.java:580)
        at android.accessibilityservice.IAccessibilityServiceConnection$Stub.onTransact(IAccessibilityServiceConnection.java:87)
        at android.os.Binder.execTransact(Binder.java:731)
[Fastbot][2023-02-09 15:54:42.984] Events injected: 1205
[Fastbot][2023-02-09 15:54:42.985] // Monkey is over!
[Fastbot][2023-02-09 15:54:42.985] :Sending rotation degree=0, persist=false
[Fastbot][2023-02-09 15:54:43.054] Total app activities:
[Fastbot][2023-02-09 15:54:43.056]    1 com.eebbk.electronicalbum.activity.ContentActivity
[Fastbot][2023-02-09 15:54:43.057]    2 com.eebbk.electronicalbum.galleryrecycler.activity.GalleryRecyclerActivity
[Fastbot][2023-02-09 15:54:43.057]    3 com.eebbk.electronicalbum.db.Wallpaper
[Fastbot][2023-02-09 15:54:43.058]    4 com.eebbk.bfc.sdk.behavior.exception.CrashReportActivity
[Fastbot][2023-02-09 15:54:43.058]    5 com.eebbk.electronicalbum.activity.MainActivity
[Fastbot][2023-02-09 15:54:43.058]    6 com.eebbk.electronicalbum.galleryrecycler.activity.RecyclerContentActivity
[Fastbot][2023-02-09 15:54:43.059]    7 com.eebbk.electronicalbum.db.CropImage
[Fastbot][2023-02-09 15:54:43.059]    8 com.eebbk.electronicalbum.activity.OutSizeRouterActivity
[Fastbot][2023-02-09 15:54:43.059]    9 com.eebbk.electronicalbum.activity.SplashActivity
[Fastbot][2023-02-09 15:54:43.059]   10 com.eebbk.electronicalbum.activity.ImgActivity
[Fastbot][2023-02-09 15:54:43.059]   11 com.eebbk.electronicalbum.activity.ThirdRouterActivity
[Fastbot][2023-02-09 15:54:43.060]   12 com.eebbk.electronicalbum.activity.ImgEditActivity
[Fastbot][2023-02-09 15:54:43.060]   13 com.yalantis.ucrop.UCropActivity
[Fastbot][2023-02-09 15:54:43.060]   14 com.eebbk.electronicalbum.db.PickKeyguardWallpaper
[Fastbot][2023-02-09 15:54:43.060]   15 com.eebbk.electronicalbum.activity.ShowSingleBitmapActivity
[Fastbot][2023-02-09 15:54:43.061] Explored app activities:
[Fastbot][2023-02-09 15:54:43.061]    1 com.eebbk.electronicalbum.activity.ContentActivity
[Fastbot][2023-02-09 15:54:43.061]    2 com.eebbk.electronicalbum.activity.ImgActivity
[Fastbot][2023-02-09 15:54:43.061]    3 com.eebbk.electronicalbum.activity.ImgEditActivity
[Fastbot][2023-02-09 15:54:43.062]    4 com.eebbk.electronicalbum.activity.MainActivity
[Fastbot][2023-02-09 15:54:43.062]    5 com.eebbk.electronicalbum.activity.SplashActivity
[Fastbot][2023-02-09 15:54:43.062]    6 com.eebbk.electronicalbum.galleryrecycler.activity.GalleryRecyclerActivity
[Fastbot][2023-02-09 15:54:43.063]    7 com.yalantis.ucrop.UCropActivity
[Fastbot][2023-02-09 15:54:43.064] Activity of Coverage: 46.666668%
:Dropped: keys=0 pointers=6 trackballs=0 flips=0 rotations=0
[Fastbot][2023-02-09 15:54:43.072] // Monkey finished

**Comment by zhangzhao4444** [comment]
这个换下同型号其他设备能否复现？ 可能系统不稳定造成

**Comment by zhangzhao4444** [comment]
试一下重启后是否能正常运行？

**Comment by hatusyoki** [comment]
> 试一下重启后是否能正常运行？

这个问题是随机发生的，重新开始有时还是会中途就停止。

**Comment by zhangzhao4444** [comment]
这个问题参考qa，运行fastbot前需要关闭其他占用accessibilityservice的进程
