### ISSUE TITLE
开始跑就卡住，这个是因为什么原因呀

### ISSUE THREAD

**Issue by hhhaiai** [bytedance/Fastbot_Android#215]
* 手机: 谷歌Pixel 4XL
* 系统: android13开发版本系统
* 日志

```
[Fastbot]*** WARNING *** // meminfo status was 01
[Fastbot]*** WARNING *** 02-15 13:45:03.599     0     0 I         : c7   5469 binder: 5469:5469 ioctl 40046210 7fdb4d5480 returned -221
[Fastbot]*** WARNING *** 02-15 13:45:03.778  1885 16647 D CoreBackPreview: Window{8feb84b u0 com.csii.csbank/com.mobile.mbank.launcher.activity.IndexActivity_}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@4a8cb41, mPriority=0}1
[Fastbot]*** WARNING *** 02-15 13:45:03.660     0     0 I         : c7   5481 binder: 5481:5481 ioctl 40046210 7feec9c3f0 returned -221
[Fastbot]*** WARNING *** 02-15 13:45:03.834  1885  2076 D AutofillManagerService: onBackKeyPressed()1
[Fastbot]*** WARNING *** 02-15 13:45:03.704     0     0 W         : c6   5486 audit: audit_lost=8191 audit_rate_limit=5 audit_backlog_limit=641
[Fastbot]*** WARNING *** 02-15 13:45:03.704     0     0 E         : c6   5486 audit: rate limit exceeded1
[Fastbot]*** WARNING *** 02-15 13:45:03.724     0     0 I         : c4   5489 binder: 5489:5489 ioctl 40046210 7fcbd74f80 returned -221
[Fastbot]*** WARNING *** 02-15 13:45:03.894  1885 11711 D CoreBackPreview: Window{6ca0aef u0 com.csii.csbank/com.mobile.mbank.launcher.activity.IndexActivity_}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@8bef801, mPriority=0}1
[Fastbot]*** WARNING *** 02-15 13:45:03.767     0     0 I         : c4   5495 binder: 5495:5495 ioctl 40046210 7fed9dab40 returned -221
[Fastbot]*** WARNING *** 02-15 13:45:03.813     0     0 I         : c6   5501 binder: 5501:5501 ioctl 40046210 7fed9c1fa0 returned -221
[Fastbot]*** WARNING *** 02-15 13:45:03.862     0     0 I         : c5   5507 binder: 5507:5507 ioctl 40046210 7fd3821620 returned -221
[Fastbot]*** WARNING *** 02-15 13:45:03.904     0     0 I         : c5   5513 binder: 5513:5513 ioctl 40046210 7fc662aec0 returned -221
[Fastbot]*** WARNING *** 02-15 13:45:04.094  1885 11711 D CoreBackPreview: Window{b15c098 u0 Splash Screen com.csii.csbank EXITING}: Setting back callback null1
[Fastbot]*** WARNING *** 02-15 13:45:03.948     0     0 I         : c6   5519 binder: 5519:5519 ioctl 40046210 7fda3a14d0 returned -221
[Fastbot]*** WARNING *** 02-15 13:45:03.991     0     0 I         : c6   5525 binder: 5525:5525 ioctl 40046210 7ffb642ee0 returned -221
[Fastbot]*** WARNING *** 02-15 13:45:04.032     0     0 I         : c6   5531 binder: 5531:5531 ioctl 40046210 7fce44c750 returned -221
[Fastbot]*** WARNING *** 02-15 13:45:04.075     0     0 I         : c5   5537 binder: 5537:5537 ioctl 40046210 7fcba7e2b0 returned -221
[Fastbot]*** WARNING *** 02-15 13:45:04.118     0     0 I         : c4   5543 binder: 5543:5543 ioctl 40046210 7ff5e25830 returned -221
[Fastbot]*** WARNING *** 02-15 13:45:04.159     0     0 I         : c4   5549 binder: 5549:5549 ioctl 40046210 7fe051c600 returned -221
[Fastbot]*** WARNING *** 02-15 13:45:04.203     0     0 I         : c5   5555 binder: 5555:5555 ioctl 40046210 7ff6826610 returned -221
```

**Comment by hhhaiai** [comment]
```
[monkey 小狮Bank-2.0.0.13]--->[Fastbot]*** WARNING *** 02-16 11:14:44.539   689   771 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 4630946523002478721 (t=54472229529000)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode: Tried to access the API:ViewConfiguration which needs to have proper configuration from a non-UI Context:com.android.documentsui.DocumentsApplication@c8212a8 The API:ViewConfiguration needs a proper configuration. Use UI contexts such as an activity or a context created via createWindowContext(Display, int, Bundle) or  createConfigurationContext(Configuration) with a proper configuration.1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode: java.lang.IllegalAccessException: Tried to access the API:ViewConfiguration which needs to have proper configuration from a non-UI Context:com.android.documentsui.DocumentsApplication@c8212a81
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.os.StrictMode.assertConfigurationContext(StrictMode.java:2295)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.view.ViewConfiguration.get(ViewConfiguration.java:526)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.view.View.<init>(View.java:5366)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.view.View.<init>(View.java:5511)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.view.ViewGroup.<init>(ViewGroup.java:703)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.widget.LinearLayout.<init>(LinearLayout.java:254)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.widget.LinearLayout.<init>(LinearLayout.java:250)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.widget.LinearLayout.<init>(LinearLayout.java:246)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at java.lang.reflect.Constructor.newInstance0(Native Method)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at java.lang.reflect.Constructor.newInstance(Constructor.java:343)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.view.LayoutInflater.createView(LayoutInflater.java:858)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.view.LayoutInflater.createView(LayoutInflater.java:780)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.view.LayoutInflater.onCreateView(LayoutInflater.java:934)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.view.LayoutInflater.onCreateView(LayoutInflater.java:954)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.view.LayoutInflater.inflate(LayoutInflater.java:686)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.view.LayoutInflater.inflate(LayoutInflater.java:538)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.view.LayoutInflater.inflate(LayoutInflater.java:485)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at com.android.documentsui.DragShadowBuilder.<init>(DragShadowBuilder.java:49)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at com.android.documentsui.DragAndDropManager$RuntimeDragAndDropManager.<init>(DragAndDropManager.java:195)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at com.android.documentsui.DragAndDropManager$RuntimeDragAndDropManager.<init>(Unknown Source:0)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at com.android.documentsui.DragAndDropManager.create(DragAndDropManager.java:163)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at com.android.documentsui.DocumentsApplication.onCreate(DocumentsApplication.java:145)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6785)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.os.Handler.dispatchMessage(Handler.java:106)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.os.Looper.loopOnce(Looper.java:201)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.os.Looper.loop(Looper.java:288)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at android.app.ActivityThread.main(ActivityThread.java:7898)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at java.lang.reflect.Method.invoke(Native Method)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)1
[Fastbot]*** WARNING *** 02-16 11:14:44.542 15126 15126 E StrictMode:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode: Tried to access the API:ViewConfiguration which needs to have proper configuration from a non-UI Context:com.android.documentsui.DocumentsApplication@c8212a8 The API:ViewConfiguration needs a proper configuration. Use UI contexts such as an activity or a context created via createWindowContext(Display, int, Bundle) or  createConfigurationContext(Configuration) with a proper configuration.1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode: java.lang.IllegalAccessException: Tried to access the API:ViewConfiguration which needs to have proper configuration from a non-UI Context:com.android.documentsui.DocumentsApplication@c8212a81
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.os.StrictMode.assertConfigurationContext(StrictMode.java:2295)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.view.ViewConfiguration.get(ViewConfiguration.java:526)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.view.View.<init>(View.java:5366)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.view.View.<init>(View.java:5511)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.widget.ImageView.<init>(ImageView.java:196)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.widget.ImageView.<init>(ImageView.java:191)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.widget.ImageView.<init>(ImageView.java:187)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at com.android.documentsui.DropBadgeView.<init>(DropBadgeView.java:40)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at java.lang.reflect.Constructor.newInstance0(Native Method)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at java.lang.reflect.Constructor.newInstance(Constructor.java:343)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.view.LayoutInflater.createView(LayoutInflater.java:858)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1237)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.view.LayoutInflater.inflate(LayoutInflater.java:686)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.view.LayoutInflater.inflate(LayoutInflater.java:538)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.view.LayoutInflater.inflate(LayoutInflater.java:485)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at com.android.documentsui.DragShadowBuilder.<init>(DragShadowBuilder.java:49)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at com.android.documentsui.DragAndDropManager$RuntimeDragAndDropManager.<init>(DragAndDropManager.java:195)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at com.android.documentsui.DragAndDropManager$RuntimeDragAndDropManager.<init>(Unknown Source:0)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at com.android.documentsui.DragAndDropManager.create(DragAndDropManager.java:163)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at com.android.documentsui.DocumentsApplication.onCreate(DocumentsApplication.java:145)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6785)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.os.Handler.dispatchMessage(Handler.java:106)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.os.Looper.loopOnce(Looper.java:201)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.os.Looper.loop(Looper.java:288)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at android.app.ActivityThread.main(ActivityThread.java:7898)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at java.lang.reflect.Method.invoke(Native Method)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)1
[Fastbot]*** WARNING *** 02-16 11:14:44.548 15126 15126 E StrictMode:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)1
[Fastbot]*** WARNING *** 02-16 11:14:44.550  1885  1899 W MediaPlayer-JNI: MediaPlayer finalized without being released1
[Fastbot]*** WARNING *** 02-16 11:14:44.550  1290 23634 D NuPlayerDriver: reset(0xf1bc19b0) at state 41
[Fastbot]*** WARNING *** 02-16 11:14:44.551  1290 15050 D NuPlayerDriver: notifyResetComplete(0xf1bc19b0)1
[Fastbot]*** WARNING *** 02-16 11:14:44.551  1885  1899 V MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false1
[Fastbot]*** WARNING *** 02-16 11:14:44.551  1885  1899 V MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null1
[Fastbot]*** WARNING *** 02-16 11:14:44.556   689   771 W HWComposer: Ignoring duplicate VSYNC event from HWC for display 4630946523002478721 (t=54472246245000)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode: Tried to access the API:ViewConfiguration which needs to have proper configuration from a non-UI Context:com.android.documentsui.DocumentsApplication@c8212a8 The API:ViewConfiguration needs a proper configuration. Use UI contexts such as an activity or a context created via createWindowContext(Display, int, Bundle) or  createConfigurationContext(Configuration) with a proper configuration.1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode: java.lang.IllegalAccessException: Tried to access the API:ViewConfiguration which needs to have proper configuration from a non-UI Context:com.android.documentsui.DocumentsApplication@c8212a81
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.os.StrictMode.assertConfigurationContext(StrictMode.java:2295)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.view.ViewConfiguration.get(ViewConfiguration.java:526)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.view.View.<init>(View.java:5366)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.view.View.<init>(View.java:5511)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.widget.TextView.<init>(TextView.java:1072)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.widget.TextView.<init>(TextView.java:1066)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.widget.TextView.<init>(TextView.java:1062)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at java.lang.reflect.Constructor.newInstance0(Native Method)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at java.lang.reflect.Constructor.newInstance(Constructor.java:343)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.view.LayoutInflater.createView(LayoutInflater.java:858)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.view.LayoutInflater.createView(LayoutInflater.java:780)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.view.LayoutInflater.onCreateView(LayoutInflater.java:934)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.view.LayoutInflater.onCreateView(LayoutInflater.java:954)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.view.LayoutInflater.inflate(LayoutInflater.java:686)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.view.LayoutInflater.inflate(LayoutInflater.java:538)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.view.LayoutInflater.inflate(LayoutInflater.java:485)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at com.android.documentsui.DragShadowBuilder.<init>(DragShadowBuilder.java:49)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at com.android.documentsui.DragAndDropManager$RuntimeDragAndDropManager.<init>(DragAndDropManager.java:195)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at com.android.documentsui.DragAndDropManager$RuntimeDragAndDropManager.<init>(Unknown Source:0)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at com.android.documentsui.DragAndDropManager.create(DragAndDropManager.java:163)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at com.android.documentsui.DocumentsApplication.onCreate(DocumentsApplication.java:145)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6785)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.os.Handler.dispatchMessage(Handler.java:106)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.os.Looper.loopOnce(Looper.java:201)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.os.Looper.loop(Looper.java:288)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at android.app.ActivityThread.main(ActivityThread.java:7898)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at java.lang.reflect.Method.invoke(Native Method)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)1
[Fastbot]*** WARNING *** 02-16 11:14:44.561 15126 15126 E StrictMode:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)1
```

**Comment by hhhaiai** [comment]
启动页面获取是否有问题呀

**Comment by zhangzhao4444** [comment]
兼容android13 近期发布，不过log上看着不像是兼容问题，回头更想版本再试下看看
