### ISSUE TITLE
支持安卓13的monkeyq跑安卓11报错 com.bytedance.fastbot.AiClient.nkksdhd

### ISSUE THREAD

**Issue by wangchy0927** [bytedance/Fastbot_Android#217]
[Fastbot][2023-03-17 10:01:12.058] // phone info： Xiaomi_M2103K19C_11
[Fastbot][2023-03-17 10:01:12.059] // runing fastbot
[Fastbot][2023-03-17 10:01:12.067] InputMethod ID: com.baidu.input_mi/.ImeService
[Fastbot][2023-03-17 10:01:12.068] InputMethod ID: com.iflytek.inputmethod.miui/.FlyIME
[Fastbot][2023-03-17 10:01:12.069] InputMethod ID: com.sohu.inputmethod.sogou.xiaomi/.SogouIME
[Fastbot][2023-03-17 10:01:12.082] // device serial number is eymr65hipffmqwso
[Fastbot][2023-03-17 10:01:12.144] // device uuid is 23997d95-11d0-41b7-bf6d-08f2e4955986
[Fastbot][2023-03-17 10:01:13.568] // init with reuse agent
[Fastbot][2023-03-17 10:01:13.582] fastbot native : library load!
[Fastbot][2023-03-17 10:01:13.587] 

[Fastbot][2023-03-17 10:01:13.591] // current activity is com.tencent.mm.plugin.fts.ui.FTSMainUI
[Fastbot][2023-03-17 10:01:13.609] // Eventid: 1
[Fastbot][2023-03-17 10:01:13.630] action type: LONG_CLICK
[Fastbot][2023-03-17 10:01:13.632] rpc cost time: 13
[Fastbot][2023-03-17 10:01:13.635] // Monkey is over!
java.lang.UnsatisfiedLinkError: No implementation found for boolean com.bytedance.fastbot.AiClient.nkksdhdk(java.lang.String, float, float) (tried Java_com_bytedance_fastbot_AiClient_nkksdhdk and Java_com_bytedance_fastbot_AiClient_nkksdhdk__Ljava_lang_String_2FF)
	at com.bytedance.fastbot.AiClient.nkksdhdk(Native Method)
	at com.bytedance.fastbot.AiClient.a(SourceFile:122)
	at com.android.commands.monkey.x.a(SourceFile:617)
	at com.android.commands.monkey.x.a(SourceFile:5659)
	at com.android.commands.monkey.x.b(SourceFile:1046)
	at com.android.commands.monkey.x.a(SourceFile:995)
	at com.android.commands.monkey.x.z(SourceFile:941)
	at com.android.commands.monkey.x.k(SourceFile:396)
	at com.android.commands.monkey.Monkey.f(SourceFile:1506)
	at com.android.commands.monkey.Monkey.a(SourceFile:868)
	at com.android.commands.monkey.Monkey.main(SourceFile:461)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:427)
[Fastbot][2023-03-17 10:01:13.653] Internal error
[Fastbot][2023-03-17 10:01:13.655] Please report this bug issue to github

**Comment by wangchy0927** [comment]
旧版本的没问题
修改时间: 2021年11月16日, 19:53:28
MD5: 6545C9CB915A4ED740956CC5236B8883
SHA1: 4DF42563F38D880C4123C6B14A78F19C2A5410F3

**Comment by wangchy0927** [comment]
更新libs解决
