### ISSUE TITLE
运行后报java.lang.NumberFormatException

### ISSUE THREAD

**Issue by ceshi2018** [bytedance/Fastbot_Android#22]
Please report this bug issue to github
java.lang.NumberFormatException: For input string: "[0"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.lang.Float.parseFloat(Float.java:451)
        at java.lang.Float.valueOf(Float.java:416)
        at com.android.a.c.a.b.b(SourceFile:134)
        at com.android.a.c.a.b.a(SourceFile:1108)
        at com.android.a.a.e.ay(SourceFile:129)
        at com.android.a.a.c.ar(SourceFile:271)
        at com.android.a.a.e.c(SourceFile:10546)
        at com.android.a.a.b.b(SourceFile:236)
        at com.android.a.a.b.a(SourceFile:226)
        at com.android.commands.monkey.y.y(SourceFile:680)
        at com.android.commands.monkey.y.l(SourceFile:1239)
        at com.android.commands.monkey.Monkey.f(SourceFile:1861)
        at com.android.commands.monkey.Monkey.a(SourceFile:1105)
        at com.android.commands.monkey.Monkey.main(SourceFile:827)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)

**Comment by ceshi2018** [comment]
pixel 4，安卓11

**Comment by ceshi2018** [comment]
CLASSPATH=/sdcard/monkey.jar:/sdcard/framework.jar exec app_process /system/bin tv.panda.test.monkey.Monkey -p com.android.dazhihui --running-minutes 450 --throttle 150 --act-whitelist-file /sdcard/awl.strings --uiautomatormix -v -v --output-directory /sdcard/max-output

用以上指令+旧的maxin跑没问题

**Comment by zhangzhao4444** [comment]
开头的version帮查下？

**Comment by zhangzhao4444** [comment]
这个排查，应该是配置错误了格式

**Comment by zhangzhao4444** [comment]
正确格式如下：
{
    "activity":"x x x",
    "bounds": "0,0,1,0.63"
}
