### ISSUE TITLE
vivo 启动报错

### ISSUE THREAD

**Issue by ljqaqq** [bytedance/Fastbot_Android#224]
[Fastbot]*** ERROR *** Error: Could not load library!
java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/local/tmp/arm64-v8a/libfastbot_native.so" not found
        at java.lang.Runtime.load0(Runtime.java:938)
        at java.lang.System.load(System.java:1631)
        at com.bytedance.fastbot.AiClient.<clinit>(SourceFile:42)
        at com.bytedance.fastbot.AiClient.a(SourceFile:73)
        at com.android.commands.monkey.x.r(SourceFile:332)
        at com.android.commands.monkey.Monkey.a(SourceFile:816)
        at com.android.commands.monkey.Monkey.main(SourceFile:461)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:372)
[Fastbot][2023-06-05 16:47:20.058] Internal error
java.lang.UnsatisfiedLinkError: No implementation found for void com.bytedance.fastbot.AiClient.fgdsaf5d(int, java.lang.String) (tried Java_com_bytedance_fastbot_AiClient_fgdsaf5d and Java_com_bytedance_fastbot_AiClient_fgdsaf5d__ILjava_lang_String_2)
        at com.bytedance.fastbot.AiClient.fgdsaf5d(Native Method)
        at com.bytedance.fastbot.AiClient.a(SourceFile:73)
        at com.android.commands.monkey.x.r(SourceFile:332)
        at com.android.commands.monkey.Monkey.a(SourceFile:816)
        at com.android.commands.monkey.Monkey.main(SourceFile:461)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:372)
[Fastbot][2023-06-05 16:47:20.061] Please report this bug issue to github
![image](https://github.com/bytedance/Fastbot_Android/assets/7824863/0ba90a34-92b7-4973-8523-21ec7a508f53)

**Comment by geron-cn** [comment]
你的截图里多了一级目录发自我的 iPhone在 2023年6月5日，16:50，ljqaqq ***@***.***> 写道：﻿
[Fastbot]*** ERROR *** Error: Could not load library!
java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/local/tmp/arm64-v8a/libfastbot_native.so" not found
at java.lang.Runtime.load0(Runtime.java:938)
at java.lang.System.load(System.java:1631)
at com.bytedance.fastbot.AiClient.(SourceFile:42)
at com.bytedance.fastbot.AiClient.a(SourceFile:73)
at com.android.commands.monkey.x.r(SourceFile:332)
at com.android.commands.monkey.Monkey.a(SourceFile:816)
at com.android.commands.monkey.Monkey.main(SourceFile:461)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:372)
[Fastbot][2023-06-05 16:47:20.058] Internal error
java.lang.UnsatisfiedLinkError: No implementation found for void com.bytedance.fastbot.AiClient.fgdsaf5d(int, java.lang.String) (tried Java_com_bytedance_fastbot_AiClient_fgdsaf5d and Java_com_bytedance_fastbot_AiClient_fgdsaf5d__ILjava_lang_String_2)
at com.bytedance.fastbot.AiClient.fgdsaf5d(Native Method)
at com.bytedance.fastbot.AiClient.a(SourceFile:73)
at com.android.commands.monkey.x.r(SourceFile:332)
at com.android.commands.monkey.Monkey.a(SourceFile:816)
at com.android.commands.monkey.Monkey.main(SourceFile:461)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:372)
[Fastbot][2023-06-05 16:47:20.061] Please report this bug issue to github
