### ISSUE TITLE
 Could not load library 报错

### ISSUE THREAD

**Issue by kane1997** [bytedance/Fastbot_Android#228]
[Fastbot][2023-06-22 11:12:57.716] // runing fastbot
[Fastbot][2023-06-22 11:12:57.730] InputMethod ID: com.google.android.tts/com.google.android.apps.speech.tts.googletts.settings.asr.voiceime.VoiceInputMethodService
[Fastbot][2023-06-22 11:12:57.731] InputMethod ID: com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME
[Fastbot][2023-06-22 11:12:57.731] InputMethod ID: com.sohu.inputmethod.sogou/.SogouIME
[Fastbot][2023-06-22 11:12:57.735] // device serial number is d85dd26c
[Fastbot][2023-06-22 11:12:57.765] // device uuid is 2547f99c-7a8e-4b05-9b72-c118ebd32771
[Fastbot][2023-06-22 11:12:59.372] // init with reuse agent
[Fastbot]*** ERROR *** Error: Could not load library!
java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/local/tmp/arm64-v8a/libfastbot_native.so" not found
        at java.lang.Runtime.load0(Runtime.java:929)
        at java.lang.System.load(System.java:1625)
        at com.bytedance.fastbot.AiClient.<clinit>(SourceFile:42)
        at com.bytedance.fastbot.AiClient.a(SourceFile:73)
        at com.android.commands.monkey.x.r(SourceFile:332)
        at com.android.commands.monkey.Monkey.a(SourceFile:816)
        at com.android.commands.monkey.Monkey.main(SourceFile:461)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:391)
[Fastbot][2023-06-22 11:12:59.387] Internal error
java.lang.UnsatisfiedLinkError: No implementation found for void com.bytedance.fastbot.AiClient.fgdsaf5d(int, java.lang.String) (tried Java_com_bytedance_fastbot_AiClient_fgdsaf5d and Java_com_bytedance_fastbot_AiClient_fgdsaf5d__ILjava_lang_String_2)
        at com.bytedance.fastbot.AiClient.fgdsaf5d(Native Method)
        at com.bytedance.fastbot.AiClient.a(SourceFile:73)
        at com.android.commands.monkey.x.r(SourceFile:332)
        at com.android.commands.monkey.Monkey.a(SourceFile:816)
        at com.android.commands.monkey.Monkey.main(SourceFile:461)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:391)
[Fastbot][2023-06-22 11:12:59.391] Please report this bug issue to github

**Comment by zhangzhao4444** [comment]
so库push路径是否正确？

**Comment by kane1997** [comment]
> 

已经解决此问题，可以close，多谢大佬
