### ISSUE TITLE
提示UiAutomationService 已经注册，如果该服务已经被其他地方注册过了，可以直接使用吗？而不是报错

### ISSUE THREAD

**Issue by xiahehe2020** [bytedance/Fastbot_Android#230]
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@7e3e486already registered!
	at android.os.Parcel.createException(Parcel.java:1961)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.view.accessibility.IAccessibilityManager$Stub$Proxy.registerUiTestAutomationService(IAccessibilityManager.java:409)
	at android.app.UiAutomationConnection.registerUiTestAutomationServiceLocked(UiAutomationConnection.java:399)
	at android.app.UiAutomationConnection.connect(UiAutomationConnection.java:97)
	at android.app.UiAutomation.connect(UiAutomation.java:238)
	at android.app.UiAutomation.connect(UiAutomation.java:214)
	at com.android.commands.monkey.x.<init>(SourceFile:2266)
	at com.android.commands.monkey.Monkey.a(SourceFile:802)
	at com.android.commands.monkey.Monkey.main(SourceFile:461)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.accessibility.UiAutomationManager.registerUiTestAutomationServiceLocked(UiAutomationManager.java:94)
	at com.android.server.accessibility.AccessibilityManagerService.registerUiTestAutomationService(AccessibilityManagerService.java:894)
	at android.view.accessibility.IAccessibilityManager$Stub.onTransact(IAccessibilityManager.java:159)
	at android.os.Binder.execTransact(Binder.java:739)

**Comment by zhangzhao4444** [comment]
请参考Q&A
