### ISSUE TITLE
 ERROR *** findMethod() error, NoSuchMethodException happened, there is no such method: setActivityController java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by chenjshnn** [bytedance/Fastbot_Android#237]
**Command**: 
adb shell \
CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar:/sdcard/fastbot-thirdpart.jar exec app_process /system/bin com.android.commands.monkey.Monkey \
-p com.twitter.android  \
--agent reuseq \
--running-minutes 10 \
--throttle 400 -v -v -v \
--app-version 

**Logcat**
[Fastbot][2023-08-28 16:17:15.124]  @Version: 2.3.23.0810.1705-git
[Fastbot]Rename /sdcard/fastbot-com.twitter.android--running-minutes-10 to /sdcard/fastbot-com.twitter.android--running-minutes-10.7
[Fastbot]Rename /sdcard/fastbot-com.twitter.android--running-minutes-10 to /sdcard/fastbot-com.twitter.android--running-minutes-10.7 succeed
[Fastbot][2023-08-28 16:17:15.128] // Monkey: seed=1693240312670 count=1000

[Fastbot][2023-08-28 16:17:15.129] // AllowPackage: com.twitter.android
[Fastbot][2023-08-28 16:17:15.129] // IncludeCategory: android.intent.category.LAUNCHER
[Fastbot][2023-08-28 16:17:15.129] // IncludeCategory: android.intent.category.MONKEY
[Fastbot]*** ERROR *** findMethod() error, NoSuchMethodException happened, there is no such method: setActivityController
[Fastbot][2023-08-28 16:17:15.142] // Selecting main activities from category android.intent.category.LAUNCHER
[Fastbot][2023-08-28 16:17:15.142] //   - NOT USING main activity com.android.calendar.AllInOneActivity (from package com.android.calendar)
[Fastbot][2023-08-28 16:17:15.143] //   - NOT USING main activity com.android.camera.CameraLauncher (from package com.android.camera2)
[Fastbot][2023-08-28 16:17:15.143] //   - NOT USING main activity com.android.contacts.activities.PeopleActivity (from package com.android.contacts)
[Fastbot][2023-08-28 16:17:15.143] //   - NOT USING main activity com.android.deskclock.DeskClock (from package com.android.deskclock)
[Fastbot][2023-08-28 16:17:15.143] //   - NOT USING main activity com.android.dialer.main.impl.MainActivity (from package com.android.dialer)
[Fastbot][2023-08-28 16:17:15.143] //   - NOT USING main activity com.android.gallery3d.app.GalleryActivity (from package com.android.gallery3d)
[Fastbot][2023-08-28 16:17:15.143] //   - NOT USING main activity com.android.messaging.ui.conversationlist.ConversationListActivity (from package com.android.messaging)
[Fastbot][2023-08-28 16:17:15.143] //   - NOT USING main activity com.android.settings.Settings (from package com.android.settings)
[Fastbot][2023-08-28 16:17:15.143] //   - NOT USING main activity com.android.vending.AssetBrowserActivity (from package com.android.vending)
[Fastbot][2023-08-28 16:17:15.143] //   - NOT USING main activity com.google.apps.dots.android.app.activity.CurrentsStartActivity (from package com.google.android.apps.magazines)
[Fastbot][2023-08-28 16:17:15.143] //   - NOT USING main activity com.spotify.music.MainActivity (from package com.spotify.music)
[Fastbot][2023-08-28 16:17:15.144] //   - NOT USING main activity tv.twitch.android.app.core.LandingActivity (from package tv.twitch.android.app)
[Fastbot][2023-08-28 16:17:15.144] //   - NOT USING main activity com.amaze.filemanager.activities.MainActivity (from package com.amaze.filemanager)
[Fastbot][2023-08-28 16:17:15.144] //   - NOT USING main activity com.android.customlocale2.CustomLocaleActivity (from package com.android.customlocale2)
[Fastbot][2023-08-28 16:17:15.144] //   - NOT USING main activity com.android.development.Development (from package com.android.development)
[Fastbot][2023-08-28 16:17:15.144] //   - NOT USING main activity android.app.AliasActivity (from package com.android.development_settings)
[Fastbot][2023-08-28 16:17:15.144] //   - NOT USING main activity com.android.documentsui.LauncherActivity (from package com.android.documentsui)
[Fastbot][2023-08-28 16:17:15.144] //   - NOT USING main activity com.android.quicksearchbox.SearchActivity (from package com.android.quicksearchbox)
[Fastbot][2023-08-28 16:17:15.144] //   - NOT USING main activity com.koushikdutta.superuser.MainActivity (from package com.genymotion.superuser)
[Fastbot][2023-08-28 16:17:15.144] //   - NOT USING main activity org.chromium.webview_shell.WebViewBrowserActivity (from package org.chromium.webview_shell)
[Fastbot][2023-08-28 16:17:15.145] //   - NOT USING main activity com.tocaboca.activity.TocaBocaMainActivity (from package com.tocaboca.tocalifeworld)
[Fastbot][2023-08-28 16:17:15.145] //   + Using main activity com.twitter.android.StartActivity (from package com.twitter.android)
[Fastbot][2023-08-28 16:17:15.145] //   - NOT USING main activity com.shein.welcome.WelcomeActivity (from package com.zzkko)
[Fastbot][2023-08-28 16:17:15.145] //   - NOT USING main activity jp.naver.line.android.activity.SplashActivity (from package jp.naver.line.android)
[Fastbot][2023-08-28 16:17:15.146] // Selecting main activities from category android.intent.category.MONKEY
[Fastbot][2023-08-28 16:17:15.146] //   - NOT USING main activity com.android.launcher3.uioverrides.QuickstepLauncher (from package com.android.launcher3)
[Fastbot][2023-08-28 16:17:15.146] //   - NOT USING main activity com.android.settings.Settings$RunningServicesActivity (from package com.android.settings)
[Fastbot][2023-08-28 16:17:15.146] //   - NOT USING main activity com.android.settings.Settings$StorageUseActivity (from package com.android.settings)
[Fastbot][2023-08-28 16:17:18.149] // phone info： Genymobile_Pixel 3 XL_11
[Fastbot][2023-08-28 16:17:18.149] // runing fastbot
[Fastbot][2023-08-28 16:17:18.152] InputMethod ID: com.android.inputmethod.latin/.LatinIME
[Fastbot][2023-08-28 16:17:18.152] InputMethod ID: com.android.adbkeyboard/.AdbIME
[Fastbot][2023-08-28 16:17:18.152] Find Keyboard: com.android.adbkeyboard/.AdbIME
[Fastbot]Power Manager says we are interactive
[Fastbot][2023-08-28 16:17:18.154] // device serial number is 
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.twitter.android.permission.RESTRICTED
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.MODIFY_AUDIO_SETTINGS
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.INTERNET
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.VIBRATE
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.READ_PROFILE
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.READ_CONTACTS
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.WAKE_LOCK
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.WRITE_EXTERNAL_STORAGE
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.google.android.providers.gsf.permission.READ_GSERVICES
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.android.launcher.permission.INSTALL_SHORTCUT
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.READ_PHONE_STATE
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.CAMERA
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.RECORD_AUDIO
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.google.android.gms.permission.AD_ID
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.ACCESS_NETWORK_STATE
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.GET_ACCOUNTS
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.BLUETOOTH
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.BLUETOOTH_CONNECT
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.SYSTEM_ALERT_WINDOW
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.ACCESS_FINE_LOCATION
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.ACCESS_COARSE_LOCATION
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.READ_MEDIA_IMAGES
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.READ_MEDIA_VIDEO
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.android.vending.CHECK_LICENSE
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.huawei.android.launcher.permission.READ_SETTINGS
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.huawei.android.launcher.permission.WRITE_SETTINGS
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.huawei.android.launcher.permission.CHANGE_BADGE
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.sonyericsson.home.permission.BROADCAST_BADGE
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.sonymobile.home.permission.PROVIDER_INSERT_BADGE
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.oppo.launcher.permission.READ_SETTINGS
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.oppo.launcher.permission.WRITE_SETTINGS
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.htc.launcher.permission.READ_SETTINGS
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.htc.launcher.permission.UPDATE_SHORTCUT
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.anddoes.launcher.permission.UPDATE_COUNT
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.sec.android.provider.badge.permission.WRITE
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.sec.android.provider.badge.permission.READ
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.POST_NOTIFICATIONS
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.AUTHENTICATE_ACCOUNTS
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.MANAGE_ACCOUNTS
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.USE_CREDENTIALS
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.READ_SYNC_SETTINGS
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.WRITE_SYNC_SETTINGS
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.ACCESS_WIFI_STATE
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.google.android.c2dm.permission.RECEIVE
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.RECEIVE_BOOT_COMPLETED
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.FOREGROUND_SERVICE
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.twitter.android.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION
[Fastbot]*** DEBUG *** com.twitter.android requrested permission com.android.vending.BILLING
[Fastbot]*** DEBUG *** com.twitter.android requrested permission android.permission.READ_EXTERNAL_STORAGE
[Fastbot][2023-08-28 16:17:18.167] // device uuid is 6c627d50-d918-4cd2-a354-e6f8f6ae4949
[Fastbot]*** INFO *** Try to grant saved permission to com.twitter.android for GrantPermissionsActivity... 
[Fastbot]*** INFO *** Grant saved permission com.twitter.android.permission.RESTRICTED to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.twitter.android.permission.RESTRICTED is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.MODIFY_AUDIO_SETTINGS to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.MODIFY_AUDIO_SETTINGS is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.INTERNET to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.INTERNET is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.VIBRATE to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.VIBRATE is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.READ_PROFILE to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.READ_PROFILE is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.READ_CONTACTS to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.READ_CONTACTS is granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.WAKE_LOCK to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.WAKE_LOCK is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.WRITE_EXTERNAL_STORAGE to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.WRITE_EXTERNAL_STORAGE is granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.google.android.providers.gsf.permission.READ_GSERVICES to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.google.android.providers.gsf.permission.READ_GSERVICES is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.android.launcher.permission.INSTALL_SHORTCUT to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.android.launcher.permission.INSTALL_SHORTCUT is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.READ_PHONE_STATE to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.READ_PHONE_STATE is granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.CAMERA to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.CAMERA is granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.RECORD_AUDIO to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.RECORD_AUDIO is granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.google.android.gms.permission.AD_ID to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.google.android.gms.permission.AD_ID is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.ACCESS_NETWORK_STATE to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.ACCESS_NETWORK_STATE is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.GET_ACCOUNTS to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.GET_ACCOUNTS is granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.BLUETOOTH to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.BLUETOOTH is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.BLUETOOTH_CONNECT to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.BLUETOOTH_CONNECT is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.SYSTEM_ALERT_WINDOW to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.SYSTEM_ALERT_WINDOW is granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.ACCESS_FINE_LOCATION to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.ACCESS_FINE_LOCATION is granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.ACCESS_COARSE_LOCATION to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.ACCESS_COARSE_LOCATION is granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.READ_MEDIA_IMAGES to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.READ_MEDIA_IMAGES is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.READ_MEDIA_VIDEO to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.READ_MEDIA_VIDEO is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.android.vending.CHECK_LICENSE to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.android.vending.CHECK_LICENSE is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.huawei.android.launcher.permission.READ_SETTINGS to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.huawei.android.launcher.permission.READ_SETTINGS is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.huawei.android.launcher.permission.WRITE_SETTINGS to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.huawei.android.launcher.permission.WRITE_SETTINGS is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.huawei.android.launcher.permission.CHANGE_BADGE to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.huawei.android.launcher.permission.CHANGE_BADGE is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.sonyericsson.home.permission.BROADCAST_BADGE to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.sonyericsson.home.permission.BROADCAST_BADGE is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.sonymobile.home.permission.PROVIDER_INSERT_BADGE to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.sonymobile.home.permission.PROVIDER_INSERT_BADGE is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.oppo.launcher.permission.READ_SETTINGS to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.oppo.launcher.permission.READ_SETTINGS is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.oppo.launcher.permission.WRITE_SETTINGS to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.oppo.launcher.permission.WRITE_SETTINGS is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.htc.launcher.permission.READ_SETTINGS to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.htc.launcher.permission.READ_SETTINGS is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.htc.launcher.permission.UPDATE_SHORTCUT to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.htc.launcher.permission.UPDATE_SHORTCUT is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.anddoes.launcher.permission.UPDATE_COUNT to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.anddoes.launcher.permission.UPDATE_COUNT is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.sec.android.provider.badge.permission.WRITE to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.sec.android.provider.badge.permission.WRITE is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.sec.android.provider.badge.permission.READ to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.sec.android.provider.badge.permission.READ is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.POST_NOTIFICATIONS to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.POST_NOTIFICATIONS is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.AUTHENTICATE_ACCOUNTS to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.AUTHENTICATE_ACCOUNTS is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.MANAGE_ACCOUNTS to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.MANAGE_ACCOUNTS is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.USE_CREDENTIALS to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.USE_CREDENTIALS is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.READ_SYNC_SETTINGS to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.READ_SYNC_SETTINGS is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.WRITE_SYNC_SETTINGS to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.WRITE_SYNC_SETTINGS is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.ACCESS_WIFI_STATE to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.ACCESS_WIFI_STATE is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.google.android.c2dm.permission.RECEIVE to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.google.android.c2dm.permission.RECEIVE is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.RECEIVE_BOOT_COMPLETED to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.RECEIVE_BOOT_COMPLETED is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.FOREGROUND_SERVICE to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.FOREGROUND_SERVICE is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.twitter.android.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.twitter.android.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission com.android.vending.BILLING to com.twitter.android... 
[Fastbot]*** INFO *** Permission com.android.vending.BILLING is NOT granted to com.twitter.android... 
[Fastbot]*** INFO *** Grant saved permission android.permission.READ_EXTERNAL_STORAGE to com.twitter.android... 
[Fastbot]*** INFO *** Permission android.permission.READ_EXTERNAL_STORAGE is granted to com.twitter.android... 
[Fastbot][2023-08-28 16:17:18.460] Internal error
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at com.android.commands.monkey.source.MonkeySourceApeNative.setAttribute(MonkeySourceApeNative.java:1342)
	at com.android.commands.monkey.Monkey.run(Monkey.java:787)
	at com.android.commands.monkey.Monkey.main(Monkey.java:460)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
[Fastbot][2023-08-28 16:17:18.461] Please report this bug issue to github

Any advice on fixing this issue? It happens occationally

**Comment by chenjshnn** [comment]
i remove --app-version and it works fine
