### ISSUE TITLE
ERROR *** findMethod() error, NoSuchMethodException happened, 

### ISSUE THREAD

**Issue by liuts933** [bytedance/Fastbot_Android#239]
[Fastbot]*** ERROR *** findMethod() error, NoSuchMethodException happened, there is no such method: setActivityController
[Fastbot][2023-08-29 14:12:13.950] // Selecting main activities from category android.intent.category.LAUNCHER
[Fastbot][2023-08-29 14:12:13.951] //   - NOT USING main activity com.android.gallery3d.app.GalleryActivity (from package com.android.gallery3d)
[Fastbot][2023-08-29 14:12:13.952] //   - NOT USING main activity com.android.settings.Settings (from package com.android.settings)
[Fastbot][2023-08-29 14:12:13.953] //   - NOT USING main activity com.android.calculator2.Calculator (from package com.google.android.calculator)
[Fastbot][2023-08-29 14:12:13.954] //   - NOT USING main activity com.mediatek.camera.CameraLauncher (from package com.mediatek.camera)
[Fastbot][2023-08-29 14:12:13.955] //   - NOT USING main activity com.dspread.demoui.activities.WelcomeActivity (from package com.dspread.demoui)
[Fastbot][2023-08-29 14:12:13.957] //   - NOT USING main activity com.android.d20selectbootanimation.MainActivity (from package com.android.d20selectbootanimation)
[Fastbot][2023-08-29 14:12:13.958] //   - NOT USING main activity com.android.stk.StkMain (from package com.android.stk)
[Fastbot][2023-08-29 14:12:13.959] //   - NOT USING main activity com.dspread.demoui.activities.WelcomeActivity (from package com.dspread.new)[Fastbot][2023-08-29 14:12:13.959] //   - NOT USING main activity com.dsp.aptmstest.activity.MainActivity (from package com.dspread.tmsapp)
[Fastbot][2023-08-29 14:12:13.960] //   + Using main activity team.op.spos.account.features.splash.SplashActivity (from package team.op.pos.alpha)
[Fastbot][2023-08-29 14:12:13.961] //   - NOT USING main activity team.op.pay.envconfigimpl.DeveloperOptionsActivity (from package team.op.pos.module.alpha)
[Fastbot][2023-08-29 14:12:13.962] //   - NOT USING main activity team.op.spos.account.features.splash.SplashActivity (from package team.op.pos.module.alpha)
[Fastbot][2023-08-29 14:12:13.966] // Selecting main activities from category android.intent.category.MONKEY

**Comment by zhangzhao4444** [comment]
这个报错可以忽略，log打印错误，实际没什么影响

**Comment by synioe** [comment]
@zhangzhao4444 实测不仅仅是打印log错误，这个报错会直接导致fastbot运行结束，运行日志：

adb shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar:/sdcard/fastbot-thirdpart.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p xxx --agent reuseq --running-minutes 10 --throttle 500
▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄
▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░▌ ▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌
▐░█▀▀▀▀▀▀▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀▀▀  ▀▀▀▀█░█▀▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀█░▌ ▀▀▀▀█░█▀▀▀▀
▐░▌          ▐░▌       ▐░▌▐░▌               ▐░▌     ▐░▌       ▐░▌▐░▌       ▐░▌     ▐░▌
▐░█▄▄▄▄▄▄▄▄▄ ▐░█▄▄▄▄▄▄▄█░▌▐░█▄▄▄▄▄▄▄▄▄      ▐░▌     ▐░█▄▄▄▄▄▄▄█░▌▐░▌       ▐░▌     ▐░▌
▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌     ▐░▌     ▐░░░░░░░░░░▌ ▐░▌       ▐░▌     ▐░▌
▐░█▀▀▀▀▀▀▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌ ▀▀▀▀▀▀▀▀▀█░▌     ▐░▌     ▐░█▀▀▀▀▀▀▀█░▌▐░▌       ▐░▌     ▐░▌
▐░▌          ▐░▌       ▐░▌          ▐░▌     ▐░▌     ▐░▌       ▐░▌▐░▌       ▐░▌     ▐░▌
▐░▌          ▐░▌       ▐░▌ ▄▄▄▄▄▄▄▄▄█░▌     ▐░▌     ▐░█▄▄▄▄▄▄▄█░▌▐░█▄▄▄▄▄▄▄█░▌     ▐░▌
▐░▌          ▐░▌       ▐░▌▐░░░░░░░░░░░▌     ▐░▌     ▐░░░░░░░░░░▌ ▐░░░░░░░░░░░▌     ▐░▌
 ▀            ▀         ▀  ▀▀▀▀▀▀▀▀▀▀▀       ▀       ▀▀▀▀▀▀▀▀▀▀   ▀▀▀▀▀▀▀▀▀▀▀       ▀
[Fastbot][2024-01-26 16:59:46.878]  @Version: 2.3.23.0810.1705-git
[Fastbot]*** ERROR *** findMethod() error, NoSuchMethodException happened, there is no such method: setActivityController
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at java.io.FileReader.<init>(FileReader.java:58)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
        at android.content.res.Resources.<init>(Resources.java:285)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
        at android.content.res.Resources.getSystem(Resources.java:206)
        at android.app.ActivityManager.isHighEndGfx(ActivityManager.java:936)
        at android.app.ActivityThread.systemMain(ActivityThread.java:7354)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.commands.monkey.utils.ContextUtils.getSystemContext(ContextUtils.java:46)
        at com.android.commands.monkey.Monkey.getMainApps(Monkey.java:1294)
        at com.android.commands.monkey.Monkey.run(Monkey.java:722)
        at com.android.commands.monkey.Monkey.main(Monkey.java:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        ... 21 more
[Fastbot][2024-01-26 16:59:49.986] // phone info： Xiaomi_M2003J15SC_10
[Fastbot][2024-01-26 16:59:49.987] // runing fastbot
[Fastbot][2024-01-26 16:59:49.996] InputMethod ID: com.google.android.googlequicksearchbox/com.google.android.voicesearch.ime.VoiceInputMethodService
[Fastbot][2024-01-26 16:59:49.997] InputMethod ID: com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME
[Fastbot][2024-01-26 16:59:50.014] // device serial number is 0d54d8d80412
[Fastbot][2024-01-26 16:59:50.036] // device uuid is bd12527e-3eda-4c9b-8d9c-93e01e041d6a
[Fastbot][2024-01-26 16:59:50.480] // init with reuse agent
[Fastbot][2024-01-26 16:59:50.488] fastbot native : library load!
[Fastbot][2024-01-26 16:59:50.489] fastbot native path is : /data/local/tmp/arm64-v8a/libfastbot_native.so

接着就直接结束运行了
