### ISSUE TITLE
Mate20 pro执行时会异常退出，详见堆栈

### ISSUE THREAD

**Issue by pxrgod** [bytedance/Fastbot_Android#24]
[1610799374860] using nstep-q agent
[1610799374860] // Display Bounds: (0,0),(1440,3120)
[1610799374860] // Monkey is over!
[1610799374861] :Sending rotation degree : 0, persist : false
[1610799374885] Running failed
java.lang.NumberFormatException: For input string: "[108"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.lang.Float.parseFloat(Float.java:451)
        at java.lang.Float.valueOf(Float.java:416)
        at com.android.a.c.a.b.b(SourceFile:134)
        at com.android.a.c.a.b.a(SourceFile:1108)
        at com.android.a.a.e.ay(SourceFile:129)
        at com.android.a.a.c.ar(SourceFile:271)
        at com.android.a.a.e.c(SourceFile:10546)
        at com.android.a.a.b.b(SourceFile:236)
        at com.android.a.a.b.a(SourceFile:226)
        at com.android.commands.monkey.y.y(SourceFile:680)
        at com.android.commands.monkey.y.l(SourceFile:1239)
        at com.android.commands.monkey.Monkey.f(SourceFile:1861)
        at com.android.commands.monkey.Monkey.a(SourceFile:1105)
        at com.android.commands.monkey.Monkey.main(SourceFile:827)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[1610799374889] Please report this bug issue to github

**Comment by zhangzhao4444** [comment]
帮看下开头version打印？

**Comment by pxrgod** [comment]
手机版本么？发自我的华为手机-------- 原始邮件 --------发件人： zhangzhao <notifications@github.com>日期： 2021年1月28日周四 晚上8:48收件人： bytedance/Fastbot_Android <Fastbot_Android@noreply.github.com>抄送： pxrgod <panxurong@163.com>, Author <author@noreply.github.com>主    题： Re: [bytedance/Fastbot_Android] Mate20 pro执行时会异常退出，详见堆栈 (#24)

帮看下开头version打印？

**Comment by pxrgod** [comment]
> 帮看下开头version打印？

2.2.1.0202.1643_git

**Comment by zhangzhao4444** [comment]
2.2.1.0304.2039_git 已修改
