### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by dah-fari7009** [bytedance/Fastbot_Android#246]
Reporting on a bug I ran into when testing Fastbot on a Google Play app (McDonalds Canada, com.mcdonalds.superapp, target sdk version=31)
▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄ 
▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░▌ ▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌
▐░█▀▀▀▀▀▀▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀▀▀  ▀▀▀▀█░█▀▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌▐░█▀▀▀▀▀▀▀█░▌ ▀▀▀▀█░█▀▀▀▀ 
▐░▌          ▐░▌       ▐░▌▐░▌               ▐░▌     ▐░▌       ▐░▌▐░▌       ▐░▌     ▐░▌     
▐░█▄▄▄▄▄▄▄▄▄ ▐░█▄▄▄▄▄▄▄█░▌▐░█▄▄▄▄▄▄▄▄▄      ▐░▌     ▐░█▄▄▄▄▄▄▄█░▌▐░▌       ▐░▌     ▐░▌     
▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌     ▐░▌     ▐░░░░░░░░░░▌ ▐░▌       ▐░▌     ▐░▌     
▐░█▀▀▀▀▀▀▀▀▀ ▐░█▀▀▀▀▀▀▀█░▌ ▀▀▀▀▀▀▀▀▀█░▌     ▐░▌     ▐░█▀▀▀▀▀▀▀█░▌▐░▌       ▐░▌     ▐░▌     
▐░▌          ▐░▌       ▐░▌          ▐░▌     ▐░▌     ▐░▌       ▐░▌▐░▌       ▐░▌     ▐░▌     
▐░▌          ▐░▌       ▐░▌ ▄▄▄▄▄▄▄▄▄█░▌     ▐░▌     ▐░█▄▄▄▄▄▄▄█░▌▐░█▄▄▄▄▄▄▄█░▌     ▐░▌     
▐░▌          ▐░▌       ▐░▌▐░░░░░░░░░░░▌     ▐░▌     ▐░░░░░░░░░░▌ ▐░░░░░░░░░░░▌     ▐░▌     
 ▀            ▀         ▀  ▀▀▀▀▀▀▀▀▀▀▀       ▀       ▀▀▀▀▀▀▀▀▀▀   ▀▀▀▀▀▀▀▀▀▀▀       ▀
[Fastbot][2023-07-29 13:43:00.288]  @Version: 2.2.03.0313.1705-git
[Fastbot][2023-07-29 13:43:00.423] // Monkey: seed=1690796407767 count=1000

[Fastbot][2023-07-29 13:43:00.423] // AllowPackage: com.mcdonalds.superapp
[Fastbot][2023-07-29 13:43:00.423] // IncludeCategory: android.intent.category.LAUNCHER
[Fastbot][2023-07-29 13:43:00.424] // IncludeCategory: android.intent.category.MONKEY
[Fastbot][2023-07-29 13:43:00.779] // Selecting main activities from category android.intent.category.LAUNCHER
[Fastbot][2023-07-29 13:43:00.779] //   - NOT USING main activity com.android.camera.CameraLauncher (from package com.android.camera2)
[Fastbot][2023-07-29 13:43:00.788] //   - NOT USING main activity com.google.android.apps.chrome.Main (from package com.android.chrome)
[Fastbot][2023-07-29 13:43:00.789] //   - NOT USING main activity com.android.contacts.activities.PeopleActivity (from package com.android.contacts)
[Fastbot][2023-07-29 13:43:00.789] //   - NOT USING main activity com.android.dialer.main.impl.MainActivity (from package com.android.dialer)
.....
com.google.android.apps.wellbeing.settings.TopLevelSettingsActivity (from package com.google.android.apps.wellbeing)
[Fastbot][2023-07-29 13:43:00.796] //   - NOT USING main activity com.google.android.googlequicksearchbox.SearchActivity (from package com.google.android.googlequicksearchbox)

```
[Fastbot][2023-07-29 13:43:00.796] Internal error
[Fastbot][2023-07-29 13:43:00.797] Please report this bug issue to github
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/GsonBuilder;
	at com.android.commands.monkey.fastbot.client.GsonIface.<clinit>(SourceFile:28)
	at com.android.commands.monkey.g.c.y(SourceFile:84)
	at com.android.commands.monkey.Monkey.a(SourceFile:756)
	at com.android.commands.monkey.Monkey.main(SourceFile:461)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
	... 6 more
```

**Comment by dah-fari7009** [comment]
Update: I tried rebuilding the tool instead of using the binaries on the repo and it worked
