### ISSUE TITLE
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@5b734d4already registered!

### ISSUE THREAD

**Issue by Pactortester** [bytedance/Fastbot_Android#266]
```bash
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@5b734d4already registered!
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3030)
	at android.os.Parcel.createException(Parcel.java:3006)
	at android.os.Parcel.readException(Parcel.java:2989)
	at android.os.Parcel.readException(Parcel.java:2931)
	at android.view.accessibility.IAccessibilityManager$Stub$Proxy.registerUiTestAutomationService(IAccessibilityManager.java:845)
	at android.app.UiAutomationConnection.registerUiTestAutomationServiceLocked(UiAutomationConnection.java:558)
	at android.app.UiAutomationConnection.connect(UiAutomationConnection.java:112)
	at android.app.UiAutomation.connectWithTimeout(UiAutomation.java:337)
	at android.app.UiAutomation.connect(UiAutomation.java:289)
	at com.android.commands.monkey.source.MonkeySourceApeNative.connect(MonkeySourceApeNative.java:292)
	at com.android.commands.monkey.source.MonkeySourceApeNative.<init>(MonkeySourceApeNative.java:266)
	at com.android.commands.monkey.Monkey.run(Monkey.java:775)
	at com.android.commands.monkey.Monkey.main(Monkey.java:458)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:398)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.accessibility.UiAutomationManager.registerUiTestAutomationServiceLocked(UiAutomationManager.java:113)
	at com.android.server.accessibility.AccessibilityManagerService.registerUiTestAutomationService(AccessibilityManagerService.java:1352)
	at android.view.accessibility.IAccessibilityManager$Stub.onTransact(IAccessibilityManager.java:441)
	at android.os.Binder.execTransactInternal(Binder.java:1318)
	at android.os.Binder.execTransact(Binder.java:1279)
callee: null 1930/3402
```

**Comment by SnoopyTlion** [comment]
同问

**Comment by SnoopyTlion** [comment]
https://github.com/bytedance/Fastbot_Android/issues/187  This link may help. You shouldn't run Fastbot and other test tools simultaneously.
