### ISSUE TITLE
【已知问题】本地消耗内存构建模型以及q值计算，性能差的设备长时间运行会出现OutOfMemoryError

### ISSUE THREAD

**Issue by xianshancom** [bytedance/Fastbot_Android#27]
[1611384606503] Exception for get action resouece: g26a2513@CLICKWidget{hashCode=-1817892424, index=0, clazz='android.widget.ImageView', resourceId='com.eeds.app:id/iv_title_left', operationTypeMask=6, scrollType=none, text='', contentDesc=''}[priority=4][throttle=500][][saturation=(1.0,1)][bounds=(0,75,102,234)]
[1611384606505] Exception for get action resouece: g26a2514@CLICKWidget{hashCode=-1426092412, index=1, clazz='android.widget.ImageView', resourceId='com.eeds.app:id/iv_title_finish', operationTypeMask=6, scrollType=none, text='', contentDesc=''}[priority=4][throttle=500][][saturation=(1.0,1)][bounds=(102,75,192,234)]
[1611384606507] Exception for get action resouece: g26a2515@SCROLL_BOTTOM_UPWidget{hashCode=2105448068, index=0, clazz='android.webkit.WebView', resourceId='com.eeds.app:id/zhangzhaopatch@-1211958893', operationTypeMask=34, scrollType=all, text='淘宝网触屏版', contentDesc=''}[priority=3][throttle=0][][saturation=(1.0,1)][bounds=(0,234,1080,1920)]
[1611384606508] Exception for get action resouece: g26a2516@SCROLL_TOP_DOWNWidget{hashCode=2105448068, index=0, clazz='android.webkit.WebView', resourceId='com.eeds.app:id/zhangzhaopatch@-1211958893', operationTypeMask=34, scrollType=all, text='淘宝网触屏版', contentDesc=''}[priority=2][throttle=0][][saturation=(1.0,1)][bounds=(0,234,1080,1920)]
[1611384606510] Exception for get action resouece: g26a2517@SCROLL_LEFT_RIGHTWidget{hashCode=2105448068, index=0, clazz='android.webkit.WebView', resourceId='com.eeds.app:id/zhangzhaopatch@-1211958893', operationTypeMask=34, scrollType=all, text='淘宝网触屏版', contentDesc=''}[priority=3][throttle=0][][saturation=(1.0,1)][bounds=(0,234,1080,1920)]
[1611384606512] Exception for get action resouece: g26a2518@SCROLL_RIGHT_LEFTWidget{hashCode=2105448068, index=0, clazz='android.webkit.WebView', resourceId='com.eeds.app:id/zhangzhaopatch@-1211958893', operationTypeMask=34, scrollType=all, text='淘宝网触屏版', contentDesc=''}[priority=2][throttle=0][][saturation=(1.0,1)][bounds=(0,234,1080,1920)]
[1611384606513] Exception for get action resouece: g26a2519@BACKg26s231@com.eeds.home.mvp.ui.activity.ContainerActivity@149229393[priority=1][throttle=0][]
[1611384606514] Exception for get action class: g26a2519@BACKg26s231@com.eeds.home.mvp.ui.activity.ContainerActivity@149229393[priority=1][throttle=0][]
[1611384606514] *** Get guitree ***
[1611384613530] // Monkey is over!
[1611384613543] :Sending rotation degree : 0, persist : false
[1611384613581] Running failed
java.lang.OutOfMemoryError: Failed to allocate a 150994952 byte allocation with 16777216 free bytes and 58MB until OOM
        at java.util.Arrays.copyOf(Arrays.java:3352)
        at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:606)
        at java.lang.StringBuffer.append(StringBuffer.java:332)
        at java.io.StringWriter.write(StringWriter.java:77)
        at org.apache.xml.serializer.ToStream.printSpace(ToStream.java:819)
        at org.apache.xml.serializer.ToStream.indent(ToStream.java:796)
        at org.apache.xml.serializer.ToStream.endElement(ToStream.java:2244)
        at org.apache.xalan.transformer.TransformerIdentityImpl.endElement(TransformerIdentityImpl.java:1102)
        at org.apache.xml.serializer.TreeWalker.endNode(TreeWalker.java:460)
        at org.apache.xml.serializer.TreeWalker.traverse(TreeWalker.java:151)
        at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:390)
        at com.android.a.d.a.bZ(SourceFile:169)
        at com.android.a.a.e.c(SourceFile:2261)
        at com.android.a.a.b.b(SourceFile:236)
        at com.android.a.a.b.a(SourceFile:226)
        at com.android.commands.monkey.y.y(SourceFile:680)
        at com.android.commands.monkey.y.l(SourceFile:1239)
        at com.android.commands.monkey.Monkey.f(SourceFile:1861)
        at com.android.commands.monkey.Monkey.a(SourceFile:1105)
        at com.android.commands.monkey.Monkey.main(SourceFile:827)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:379)
[1611384613647] Please report this bug issue to github

**Comment by zhangzhao4444** [comment]
已知问题，暂时先备忘，后续找新方法解决

**Comment by zhangzhao4444** [comment]
2.2.01.0824.1351-git 版本已修改
