### ISSUE TITLE
执行命令后提示java.lang.NumberFormatException

### ISSUE THREAD

**Issue by jeniva** [bytedance/Fastbot_Android#28]
![image](https://user-images.githubusercontent.com/8514029/105328831-6db66e00-5c0b-11eb-8608-787686bb7d8f.png)
 <node index="3" text="" resource-id="com.ezviz:id/tab_more_layout" class="android.widget.RelativeLayout" content-desc="" package="com.ezviz" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" scroll-type="none" bounds="[720,2166][1080,2316]"/>
</node>

[1611219982112] using nstep-q agent
[1611219982112] // Display Bounds: (0,0),(1080,2316)
[1611219982112] // Monkey is over!
[1611219982113] :Sending rotation degree : 0, persist : false
[1611219982126] Running failed
java.lang.NumberFormatException: For input string: "[216"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.lang.Float.parseFloat(Float.java:451)
        at java.lang.Float.valueOf(Float.java:416)
        at com.android.a.c.a.b.b(SourceFile:134)
        at com.android.a.c.a.b.a(SourceFile:1108)
        at com.android.a.a.e.ay(SourceFile:129)
        at com.android.a.a.c.ar(SourceFile:271)
        at com.android.a.a.e.c(SourceFile:10546)
        at com.android.a.a.b.b(SourceFile:236)
        at com.android.a.a.b.a(SourceFile:226)
        at com.android.commands.monkey.y.y(SourceFile:680)
        at com.android.commands.monkey.y.l(SourceFile:1239)
[1611219982128] Please report this bug issue to github
        at com.android.commands.monkey.Monkey.f(SourceFile:1861)
        at com.android.commands.monkey.Monkey.a(SourceFile:1105)
        at com.android.commands.monkey.Monkey.main(SourceFile:827)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:383)

**Comment by zhangzhao4444** [comment]
开头有个version帮查一下是多少

**Comment by pxrgod** [comment]
2.2.1.0202.1643_git

> 开头有个version帮查一下是多少

2.2.1.0202.1643_git

**Comment by zhangzhao4444** [comment]
2.2.1.0304.2039_git 已修改
