### ISSUE TITLE
A15报错

### ISSUE THREAD

**Issue by Wind-Yi** [bytedance/Fastbot_Android#281]
[Fastbot][2024-05-13 18:35:13.497] Internal error
java.lang.NoSuchMethodError: No interface method freezeRotation(I)V in class Landroid/view/IWindowManager; or its super classes (declaration of 'android.view.IWindowManager' appears in /system/framework/framework.jar!classes4.dex)
        at com.android.commands.monkey.events.base.MonkeyRotationEvent.injectEvent(MonkeyRotationEvent.java:55)
        at com.android.commands.monkey.Monkey.run(Monkey.java:836)
        at com.android.commands.monkey.Monkey.main(Monkey.java:460)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:470)
[Fastbot][2024-05-13 18:35:13.498] Please report this bug issue to github

**Comment by ShawnPanxiaoming** [comment]
目前来看，Android 15 开发者预览版会报这个错，不确定后续正式版会不会好
我这边的临时方案是把MonkeyRotationEvent.java 里的injectEvent 方法内容给注释掉，先屏蔽转屏事件，直接返回MonkeyEvent.INJECT_SUCCESS，重新打包monkeyq.jar推送至Android 15设备，目前来看可以跑

**Comment by yinkh** [comment]
> 目前来看，Android 15 开发者预览版会报这个错，不确定后续正式版会不会好 我这边的临时方案是把MonkeyRotationEvent.java 里的injectEvent 方法内容给注释掉，先屏蔽转屏事件，直接返回MonkeyEvent.INJECT_SUCCESS，重新打包monkeyq.jar推送至Android 15设备，目前来看可以跑

试了下，打出来的包确实可以用了！

**Comment by yinkh** [comment]
通过百度网盘分享的文件：monkeyq.…
链接:https://pan.baidu.com/s/1px8tAHS8wAYjNx3QGkn9Aw 
提取码:k8uw
复制这段内容打开「百度网盘APP 即可获取」

**Comment by lilylei665** [comment]
> 通过百度网盘分享的文件：monkeyq.… 链接:[https://pan.baidu.com/s/1px8tAHS8wAYjNx3QGkn9Aw ](https://pan.baidu.com/s/1px8tAHS8wAYjNx3QGkn9Aw%C2%A0) 提取码:k8uw 复制这段内容打开「百度网盘APP 即可获取」
好人。运行起来了

**Comment by XixianLiang** [comment]
Kea2 支持了 Android 15，底层用的Fastbot(我们继续维护了，支持了Android 15)，可以尝试下。
https://github.com/ecnusse/Kea2
