### ISSUE TITLE
Android V执行Fastbot报错

### ISSUE THREAD

**Issue by luofengwang** [bytedance/Fastbot_Android#283]
[Fastbot][2024-05-18 18:26:54.559] Sleeping for 2000 milliseconds
[Fastbot][2024-05-18 18:26:56.561] // current activity is com.android.camera.CameraActivity
[Fastbot][2024-05-18 18:26:56.570] // Event id: 3
[Fastbot][2024-05-18 18:26:56.602] action type: CLICK
[Fastbot][2024-05-18 18:26:56.602] rpc cost time: 26
[Fastbot][2024-05-18 18:26:56.660]   minputshown=false
[Fastbot][2024-05-18 18:26:56.913] mInputShown not found, getInputMethodWindowVisibleHeight is used.
[Fastbot][2024-05-18 18:26:56.916]  event time:352
[Fastbot][2024-05-18 18:26:56.916] :Sending rotation degree=0, persist=false
[Fastbot][2024-05-18 18:26:56.917] // Monkey is over!
[Fastbot][2024-05-18 18:26:56.918] :Sending rotation degree=0, persist=false
[Fastbot][2024-05-18 18:26:56.919] Internal error
java.lang.NoSuchMethodError: No interface method freezeRotation(I)V in class Landroid/view/IWindowManager; or its super classes (declaration of 'android.view.IWindowManager' appears in /system/framework/framework.jar!classes4.dex)
        at com.android.commands.monkey.events.base.MonkeyRotationEvent.injectEvent(MonkeyRotationEvent.java:55)
        at com.android.commands.monkey.Monkey.run(Monkey.java:834)
        at com.android.commands.monkey.Monkey.main(Monkey.java:458)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:390)
[Fastbot][2024-05-18 18:26:56.922] Please report this bug issue to github

**Comment by 1649900265** [comment]
没人跟进吗

**Comment by yinkh** [comment]
通过百度网盘分享的文件：monkeyq.…
链接:https://pan.baidu.com/s/1px8tAHS8wAYjNx3QGkn9Aw 
提取码:k8uw
复制这段内容打开「百度网盘APP 即可获取」

**Comment by codecat007** [comment]
Android V遇到相同的问题+1

**Comment by milotian** [comment]
+1

**Comment by gfollower** [comment]
+1
