### ISSUE TITLE
看下呢 Failed to allocate a 51264 byte

### ISSUE THREAD

**Issue by huangshaotain** [bytedance/Fastbot_Android#29]
java.lang.OutOfMemoryError: Failed to allocate a 51264 byte allocation with 4896 free bytes and 4KB until OOM, max allowed footprint 268435456, growth limit 268435456
        at java.lang.StringFactory.newStringFromChars(StringFactory.java:220)
        at java.lang.StringBuffer.toString(StringBuffer.java:671)
        at java.io.StringWriter.toString(StringWriter.java:210)
        at com.android.a.d.a.bZ(SourceFile:170)
        at com.android.a.a.e.c(SourceFile:2261)
        at com.android.a.a.b.b(SourceFile:236)
        at com.android.a.a.b.a(SourceFile:226)
        at com.android.commands.monkey.y.y(SourceFile:680)
        at com.android.commands.monkey.y.l(SourceFile:1239)
        at com.android.commands.monkey.Monkey.f(SourceFile:1861)
        at com.android.commands.monkey.Monkey.a(SourceFile:1105)
        at com.android.commands.monkey.Monkey.main(SourceFile:827)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)

**Comment by zhangzhao4444** [comment]
shell 开头version帮提供下？

**Comment by zhangzhao4444** [comment]
与/issues/27为相同问题
