### ISSUE TITLE
java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by iris945** [bytedance/Fastbot_Android#290]
[Fastbot][2024-07-05 17:01:39.401] Internal error
java.lang.IncompatibleClassChangeError: The method 'java.lang.Class java.lang.Object.getClass()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'com.android.commands.monkey.framework.APIAdapter' appears in /sdcard/monkeyq.jar)
	at com.android.commands.monkey.framework.APIAdapter.setActivityController(APIAdapter.java:196)
	at com.android.commands.monkey.Monkey.getSystemInterfaces(Monkey.java:1283)
	at com.android.commands.monkey.Monkey.run(Monkey.java:718)
	at com.android.commands.monkey.Monkey.main(Monkey.java:460)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:389)
[Fastbot][2024-07-05 17:01:39.402] Please report this bug issue to github

**Comment by weibinfang** [comment]
同样遇到这个问题，只在一台OPPO A79 Android 7的机子上复现，查了网上几种方式，包括升级gps也不行，放弃这个机型

**Comment by lixiaoming233** [comment]
> 同样遇到这个问题，只在一台OPPO A79 Android 7的机子上复现，查了网上几种方式，包括升级gps也不行，放弃这个机型

我也在Android7的手机上遇到了同样的问题，升级Android8.0-8.1依然报错。
请问解决以上问题了嘛，使用的sdk与build tools是哪个版本的？

**Comment by majuzi123** [comment]
This issue is caused by compiling with JDK 21 on Windows System, which generates bytecode version 65 that is incompatible with the Dalvik/ART runtime on older Android devices (especially Android 6–11), leading to . The fix is to simply downgrade to JDK 17 (or lower) and rebuild monkeyq.jar — no code changes required.
