### ISSUE TITLE
Internal error google手机一运行就报错

### ISSUE THREAD

**Issue by lilylei665** [bytedance/Fastbot_Android#299]
google手机一运行就报错

**Comment by lilylei665** [comment]
[Fastbot][2024-09-09 16:43:45.340] Internal error
java.lang.NoSuchMethodError: No interface method freezeRotation(I)V in class Landroid/view/IWindowManager; or its super classes (declaration of 'android.view.IWindowManager' appears in /system/framework/framework.jar!classes4.dex)
	at com.android.commands.monkey.events.base.MonkeyRotationEvent.injectEvent(MonkeyRotationEvent.java:55)
	at com.android.commands.monkey.Monkey.run(Monkey.java:836)
	at com.android.commands.monkey.Monkey.main(Monkey.java:460)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)

**Comment by liebeschnee** [comment]
我也遇到了这个问题，请问如何解决

**Comment by zhouwei1988** [comment]
同意问题询问

**Comment by liebeschnee** [comment]
> 同意问题询问

我下载了之前评论里面monkeyq文件，替换掉原来的，在google原生V项目上可以正常运行了

链接:https://pan.baidu.com/s/1px8tAHS8wAYjNx3QGkn9Aw 
提取码:k8uw

**Comment by liebeschnee** [comment]
@lilylei665

**Comment by zhouwei1988** [comment]
> > 同意问题询问
> 
> 我下载了之前评论里面monkeyq文件，替换掉原来的，在google原生V项目上可以正常运行了
> 
> 链接:https://pan.baidu.com/s/1px8tAHS8wAYjNx3QGkn9Aw 提取码:k8uw

多谢，确实可以了
