### ISSUE TITLE
测试程序异常退出  java.lang.NoSuchMethodError: No interface method freezeRotation(I)V in class Landroid/view/IWindowManager; or its super classes (declaration of 'android.view.IWindowManager' appears in /system/framework/framework.jar!classes4.dex)

### ISSUE THREAD

**Issue by eternity-wws** [bytedance/Fastbot_Android#303]
[Fastbot][2024-10-22 19:40:27.383] fastbot native : library load!
[Fastbot][2024-10-22 19:40:27.384] fastbot native path is : /data/local/tmp/arm64-v8a/libfastbot_native.so
[Fastbot][2024-10-22 19:40:27.390] 

[Fastbot]*** ERROR *** findMethod() error, NoSuchMethodException happened, there is no such method: getTasks
[Fastbot][2024-10-22 19:40:27.395] // current activity is com.android.camera.Camera
[Fastbot][2024-10-22 19:40:27.413] // Event id: 1
[Fastbot][2024-10-22 19:40:27.439] action type: SCROLL_LEFT_RIGHT
[Fastbot][2024-10-22 19:40:27.439] rpc cost time: 11
[Fastbot][2024-10-22 19:40:27.444]  event time:48
[Fastbot][2024-10-22 19:40:27.444] :Sending rotation degree=0, persist=false
[Fastbot][2024-10-22 19:40:27.445] // Monkey is over!
[Fastbot][2024-10-22 19:40:27.445] :Sending rotation degree=0, persist=false
[Fastbot][2024-10-22 19:40:27.445] Internal error
java.lang.NoSuchMethodError: No interface method freezeRotation(I)V in class Landroid/view/IWindowManager; or its super classes (declaration of 'android.view.IWindowManager' appears in /system/framework/framework.jar!classes4.dex)
	at com.android.commands.monkey.events.base.MonkeyRotationEvent.injectEvent(MonkeyRotationEvent.java:55)
	at com.android.commands.monkey.Monkey.run(Monkey.java:834)
	at com.android.commands.monkey.Monkey.main(Monkey.java:458)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:382)
[Fastbot][2024-10-22 19:40:27.446] Please report this bug issue to github

**Comment by sinianGitHub** [comment]
java.lang.NoSuchMethodError: No interface method freezeRotation(I)V in class Landroid/view/IWindowManager; or its super classes (declaration of 'android.view.IWindowManager' appears in /system/framework/framework.jar!classes4.dex)
我也出现这个问题。

**Comment by yang1101122** [comment]
我也出现该问题，是系统兼容原因吗？

**Comment by eternity-wws** [comment]
> java.lang.NoSuchMethodError: No interface method freezeRotation(I)V in class Landroid/view/IWindowManager; or its super classes (declaration of 'android.view.IWindowManager' appears in /system/framework/framework.jar!classes4.dex) 我也出现这个问题。
--------------------------》
咨询下，还有类似的遍历APP功能的开源软件推荐吗？

**Comment by liebeschnee** [comment]
我也出现了这个问题

**Comment by caiye1985** [comment]
在GooglePixel 6，Android 14、15上出现了此问题

**Comment by liebeschnee** [comment]
@caiye1985 @eternity-wws @yang1101122 @sinianGitHub 
之前的评论区有个这个文件替换掉原先的就可以解决该问题了
链接:https://pan.baidu.com/s/1px8tAHS8wAYjNx3QGkn9Aw 
提取码:k8uw

**Comment by PAULouis863** [comment]
我换成真机进行测试是不会报错的，用安卓模拟器进行测试就会报错
