### ISSUE TITLE
version为2.2.1.0202.1643_git，执行时报java.lang.NumberFormatException，麻烦看下

### ISSUE THREAD

**Issue by pxrgod** [bytedance/Fastbot_Android#31]
java.lang.NumberFormatException: For input string: "[43"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.lang.Float.parseFloat(Float.java:451)
        at java.lang.Float.valueOf(Float.java:416)
        at com.android.a.c.a.b.b(SourceFile:134)
        at com.android.a.c.a.b.a(SourceFile:1108)
        at com.android.a.a.e.ay(SourceFile:131)
        at com.android.a.a.c.ar(SourceFile:330)
        at com.android.a.a.e.c(SourceFile:10548)
        at com.android.a.a.b.b(SourceFile:236)
        at com.android.a.a.b.a(SourceFile:226)
        at com.android.commands.monkey.y.y(SourceFile:681)
        at com.android.commands.monkey.y.l(SourceFile:1259)
        at com.android.commands.monkey.Monkey.f(SourceFile:1861)
        at com.android.commands.monkey.Monkey.a(SourceFile:1105)
        at com.android.commands.monkey.Monkey.main(SourceFile:827)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

**Comment by zhangzhao4444** [comment]
2.2.1.0304.2039_git 已修改
