### ISSUE TITLE
点击cocos2D控件报错

### ISSUE THREAD

**Issue by xiaodududu** [bytedance/Fastbot_Android#38]
[1615972176924] New  state: g0s2@com.hxhdxd.kaxda.module.courseplayer.HDCourseVideoPlayerActivity@1695406497
[1615972176925] New action: g0a46@CLICKWidget{hashCode=820498306, index=0, clazz='android.widget.TextView', resourceId='com.hxhdxd.kaxda:id/zhangzhaopatch@897060', operationTypeMask=6, scrollType=none, text='流畅', contentDesc=''}[priority=24][throttle=200][][saturation=(0.0,1)][bounds=(1538,725,2176,874)]
[1615972176925] *** Inject event ***
[1615972176927] :Sending Touch (ACTION_DOWN): 0:(1857.0,799.5)
[1615972176932] :Sending Touch (ACTION_UP): 0:(1857.0,799.5)
[1615972176936] Sleep for 0 ms
[1615972176938] Sleep for 800 ms
[1615972177742] Sleep for 0 ms
[1615972177765] // Monkey is over!
[1615972177766] :Sending rotation degree : 0, persist : false
[1615972177785] Running failed
java.lang.IllegalStateException: Already in the pool!
	at android.util.Pools$SimplePool.release(Pools.java:112)
	at android.util.Pools$SynchronizedPool.release(Pools.java:168)
	at android.view.accessibility.AccessibilityNodeInfo.recycle(AccessibilityNodeInfo.java:3156)
	at android.view.accessibility.AccessibilityCache.add(AccessibilityCache.java:330)
	at android.view.accessibility.AccessibilityInteractionClient.finalizeAndCacheAccessibilityNodeInfo(AccessibilityInteractionClient.java:811)
	at android.view.accessibility.AccessibilityInteractionClient.finalizeAndCacheAccessibilityNodeInfos(AccessibilityInteractionClient.java:831)
	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:352)[1615972177788] Please report this bug issue to github

	at android.view.accessibility.AccessibilityInteractionClient.getRootInActiveWindow(AccessibilityInteractionClient.java:207)
	at android.app.UiAutomation.getRootInActiveWindow(UiAutomation.java:495)
	at com.android.commands.monkey.y.y(SourceFile:11448)
	at com.android.commands.monkey.y.l(SourceFile:1259)
	at com.android.commands.monkey.Monkey.f(SourceFile:1861)
	at com.android.commands.monkey.Monkey.a(SourceFile:1105)
	at com.android.commands.monkey.Monkey.main(SourceFile:827)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:352)

**Comment by zhangzhao4444** [comment]
2.2.01.0824.1351-git 已修改可以验证下
