### ISSUE TITLE
步步高s5学习机问题

### ISSUE THREAD

**Issue by xiaodududu** [bytedance/Fastbot_Android#39]
[1616032712346] Sleep for 0 ms
[1616032712367] // Monkey is over!
[1616032712371] :Sending rotation degree : 0, persist : false
[1616032712403] Running failed
java.lang.IllegalStateException: Already in the pool!
	at android.util.Pools$SimplePool.release(Pools.java:112)
	at android.util.Pools$SynchronizedPool.release(Pools.java:168)
	at android.view.accessibility.AccessibilityNodeInfo.recycle(AccessibilityNodeInfo.java:3156)
	at android.view.accessibility.AccessibilityCache.add(AccessibilityCache.java:330)
	at android.view.accessibility.AccessibilityInteractionClient.finalizeAndCacheAccessibilityNodeInfo(AccessibilityInteractionClient.java:811)
	at android.view.accessibility.AccessibilityInteractionClient.finalizeAndCacheAccessibilityNodeInfos(AccessibilityInteractionClient.java:831)
	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:352)
	at android.view.accessibility.AccessibilityInteractionClient.getRootInActiveWindow(AccessibilityInteractionClient.java:207)
	at android.app.UiAutomation.getRootInActiveWindow(UiAutomation.java:495)
	at com.android.commands.monkey.y.y(SourceFile:11448)
	at com.android.commands.monkey.y.l(SourceFile:1259)
	at com.android.commands.monkey.Monkey.f(SourceFile:1861)
	at com.android.commands.monkey.Monkey.a(SourceFile:1105)[1616032712406] Please report this bug issue to github

	at com.android.commands.monkey.Monkey.main(SourceFile:827)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:352)

**Comment by zhangzhao4444** [comment]
2.2.01.0824.1351-git 请用新版本再试一下
