### ISSUE TITLE
测试机型：redmi 9T    使用过程中monkey不能正常执行

### ISSUE THREAD

**Issue by MynameBinGe** [bytedance/Fastbot_Android#43]
java.lang.OutOfMemoryError: Failed to allocate a 21296 byte allocation with 11584 free bytes and 11KB until OOM, target footprint 134217728, growth limit 134217728
        at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
        at java.lang.StringBuffer.toString(StringBuffer.java:671)
        at java.io.StringWriter.toString(StringWriter.java:210)
        at com.android.a.d.a.cc(SourceFile:170)
        at com.android.a.a.e.c(SourceFile:2263)
        at com.android.a.a.b.b(SourceFile:236)
        at com.android.a.a.b.a(SourceFile:226)
        at com.android.commands.monkey.y.y(SourceFile:681)
        at com.android.commands.monkey.y.l(SourceFile:1259)
        at com.android.commands.monkey.Monkey.f(SourceFile:1861)
        at com.android.commands.monkey.Monkey.a(SourceFile:1105)
        at com.android.commands.monkey.Monkey.main(SourceFile:827)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:419)
[1619455282544] Please report this bug issue to github

**Comment by MynameBinGe** [comment]
[1619669772256] Running failed
java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
        at android.os.Parcel.createException(Parcel.java:2074)
        at android.os.Parcel.readException(Parcel.java:2042)
        at android.os.Parcel.readException(Parcel.java:1990)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(IInputManager.java:925)
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:886)
        at com.android.commands.monkey.p.a(SourceFile:132)
        at com.android.commands.monkey.Monkey.f(SourceFile:1863)
        at com.android.commands.monkey.Monkey.a(SourceFile:1105)
        at com.android.commands.monkey.Monkey.main(SourceFile:827)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
[1619669772257] Please report this bug issue to github

**Comment by geron-cn** [comment]
参照手册中 Q&A， redmi 需要设置下对应权限

**Comment by zhangzhao4444** [comment]
oom问题2.2.01.0824.1351-git已修改
