### ISSUE TITLE
max.widget.black报错：java.lang.NumberFormatException

### ISSUE THREAD

**Issue by zhouycc** [bytedance/Fastbot_Android#45]
[1623934395618]  @Version : 2.2.1.0304.2039_git
[1623934395653] // Monkey : seed=1624036500254 count=1000

[1623934395654] // Valid Package: com.tal.tiku
[1623934395655] // IncludeCategory : android.intent.category.LAUNCHER
[1623934395655] // IncludeCategory : android.intent.category.MONKEY
[1623934395688] // Selecting main activities from category android.intent.category.LAUNCHER
[1623934395689] //   - NOT USING main activity com.mail139.about.LaunchActivity (from package cn.cj.pe)
[1623934395690] //   - NOT USING main activity com.android.calendar.AllInOneActivity (from package com.android.calendar)
[1623934395690] //   - NOT USING main activity com.android.contacts.activities.PeopleActivity (from package com.android.contacts)
[1623934395690] //   - NOT USING main activity com.android.contacts.activities.DialtactsActivity (from package com.android.contacts)
[1623934395691] //   - NOT USING main activity com.android.deskclock.AlarmsMainActivity (from package com.android.deskclock)
[1623934395691] //   - NOT USING main activity com.android.email.activity.Welcome (from package com.android.email)
[1623934395691] //   - NOT USING main activity com.huawei.gallery.app.GalleryMain (from package com.android.gallery3d)
[1623934395691] //   - NOT USING main activity com.android.mediacenter.PageActivity (from package com.android.mediacenter)
[1623934395691] //   - NOT USING main activity com.android.mms.ui.ConversationList (from package com.android.mms)
[1623934395692] //   - NOT USING main activity com.android.settings.HWSettings (from package com.android.settings)
[1623934395692] //   - NOT USING main activity com.example.android.notepad.NotePadActivity (from package com.example.android.notepad)
[1623934395692] //   - NOT USING main activity com.huawei.FMRadio.page.PageActivity (from package com.huawei.android.FMRadio)
[1623934395692] //   - NOT USING main activity com.huawei.android.findmyphone.ui.findphone.FindMyPhoneActivity (from package com.huawei.android.findmyphone)
[1623934395692] //   - NOT USING main activity com.huawei.android.tips.DrawerDisplayActivity (from package com.huawei.android.tips)
[1623934395693] //   - NOT USING main activity com.huawei.camera (from package com.huawei.camera)
[1623934395693] //   - NOT USING main activity com.huawei.gamebox.GameBoxActivity (from package com.huawei.gamebox)
[1623934395693] //   - NOT USING main activity com.huawei.hidisk.filemanager.FileManager (from package com.huawei.hidisk)
[1623934395693] //   - NOT USING main activity com.huawei.himovie.ui.login.SplashScreenActivity (from package com.huawei.himovie)
[1623934395693] //   - NOT USING main activity com.baidu.baidumaps.WelcomeScreen (from package com.baidu.BaiduMap)
[1623934395694] //   - NOT USING main activity com.yxcorp.gifshow.HomeActivity (from package com.smile.gifmaker)
[1623934395694] //   - NOT USING main activity com.android.browser.SplashActivity (from package com.android.browser)
[1623934395694] //   - NOT USING main activity com.android.calculator2.Calculator (from package com.android.calculator2)
[1623934395694] //   - NOT USING main activity com.android.documentsui.LauncherActivity (from package com.android.documentsui)
[1623934395694] //   - NOT USING main activity com.android.mediacenter.PageActivity (from package com.android.imedia.syncplay)
[1623934395695] //   - NOT USING main activity com.android.soundrecorder.RecordListActivity (from package com.android.soundrecorder)
[1623934395695] //   - NOT USING main activity com.android.stk.StkLauncherActivity (from package com.android.stk)
[1623934395695] //   - NOT USING main activity com.android.stk.StkLauncherActivity2 (from package com.android.stk)
[1623934395695] //   - NOT USING main activity com.android.systemui.flashlight.FlashlightActivity (from package com.android.systemui)
[1623934395695] //   - NOT USING main activity com.cmcc.cmvideo.splash.SplashActivity (from package com.cmcc.cmvideo)
[1623934395696] //   - NOT USING main activity com.cmic.mmnes.activity.SplashActivity (from package com.cmic.mmnes)
[1623934395696] //   - NOT USING main activity com.mc10086.cmcc.base.StartPageActivity (from package com.greenpoint.android.mc10086.activity)
[1623934395696] //   - NOT USING main activity com.huawei.android.clone.activity.sender.ChooseReceiveSendActivity (from package com.hicloud.android.clone)
[1623934395696] //   - NOT USING main activity com.huawei.android.hwouc.ui.activities.MainEntranceActivity (from package com.huawei.android.hwouc)
[1623934395697] //   - NOT USING main activity com.huawei.android.thememanager.mvp.view.activity.onlinebase.PageActivity (from package com.huawei.android.thememanager)
[1623934395697] //   - NOT USING main activity com.huawei.android.totemweather.WeatherHome (from package com.huawei.android.totemweather)
[1623934395697] //   - NOT USING main activity com.huawei.appmarket.MainActivity (from package com.huawei.appmarket)
[1623934395698] //   - NOT USING main activity com.huawei.gameassistant.views.GameassistantMainActivity (from package com.huawei.gameassistant)
[1623934395698] //   - NOT USING main activity com.dzbook.activity.SplashActivity (from package com.huawei.hwread.al)
[1623934395698] //   - NOT USING main activity com.huawei.mycenter.module.main.view.MainActivity (from package com.huawei.mycenter)
[1623934395699] //   - NOT USING main activity com.huawei.phoneservice.LaunchActivity (from package com.huawei.phoneservice)
[1623934395699] //   - NOT USING main activity com.huawei.systemmanager.mainscreen.MainScreenActivity (from package com.huawei.systemmanager)
[1623934395699] //   - NOT USING main activity com.huawei.trustspace.mainscreen.LoadActivity (from package com.huawei.trustspace)
[1623934395700] //   - NOT USING main activity com.huawei.vassistant.ui.main.VAssistantActivity (from package com.huawei.vassistant)
[1623934395700] //   - NOT USING main activity com.vmall.client.splash.fragment.SplashActivity (from package com.vmall.client)
[1623934395700] //   - NOT USING main activity cn.wps.moffice.documentmanager.PreStartActivity (from package cn.wps.moffice_eng)
[1623934395701] //   - NOT USING main activity com.mqunar.splash.SplashActivity (from package com.Qunar)
[1623934395701] //   - NOT USING main activity com.baidu.searchbox.SplashActivity (from package com.baidu.searchbox)
[1623934395701] //   - NOT USING main activity com.dianping.v1.NovaMainActivity (from package com.dianping.v1)
[1623934395702] //   - NOT USING main activity com.github.uiautomator.MainActivity (from package com.github.uiautomator)
[1623934395702] //   - NOT USING main activity com.jingdong.app.mall.main.MainActivity (from package com.jingdong.app.mall)
[1623934395702] //   - NOT USING main activity com.meituan.android.pt.homepage.activity.MainActivity (from package com.sankuai.meituan)
[1623934395702] //   - NOT USING main activity com.sina.weibo.SplashActivity (from package com.sina.weibo)
[1623934395702] //   - NOT USING main activity com.ss.android.article.news.activity.MainActivity (from package com.ss.android.article.news)
[1623934395703] //   + Using main activity com.tal.tiku.splash.SplashActivity (from package com.tal.tiku)
[1623934395703] //   - NOT USING main activity com.taobao.tao.welcome.Welcome (from package com.taobao.taobao)
[1623934395703] //   - NOT USING main activity com.tencent.mobileqq.activity.SplashActivity (from package com.tencent.mobileqq)
[1623934395703] //   - NOT USING main activity com.tencent.mtt.SplashActivity (from package com.tencent.mtt)
[1623934395704] //   - NOT USING main activity com.tencent.news.activity.SplashActivity (from package com.tencent.news)
[1623934395704] //   - NOT USING main activity com.tencent.qnet.Component.LoginActivity (from package com.tencent.qnet)
[1623934395704] //   - NOT USING main activity io.appium.settings.Settings (from package io.appium.settings)
[1623934395707] // Selecting main activities from category android.intent.category.MONKEY
[1623934395708] //   - NOT USING main activity com.android.settings.Settings$RunningServicesActivity (from package com.android.settings)
[1623934395709] //   - NOT USING main activity com.android.settings.Settings$StorageUseActivity (from package com.android.settings)
[1623934395709] //   - NOT USING main activity com.huawei.android.launcher.unihome.UniHomeLauncher (from package com.huawei.android.launcher)
[1623934395710] //   - NOT USING main activity com.huawei.KoBackup.InitializeActivity (from package com.huawei.KoBackup)
[1623934398765] // Special Event:
[1623934398766] // Event0:
[1623934398767] // Prob: 1.0
[1623934398767] // Activity: com.tal.user.login.CodeLoginActivity
[1623934398767] // Times: 1
[1623934398768]   // Step0:
[1623934398769]     //XPath: //*[@resource-id='com.tal.tiku:id/arg' and @text='请输入手机号']
[1623934398770]     //XPathExpression: org.apache.xpath.jaxp.XPathExpressionImpl@a94c697
[1623934398770]     //Action: CLICK
[1623934398771]     //Text: 13310894227
[1623934398771]     //Duration: 0
[1623934398772]     //Throttle: 1000
[1623934398772]   // Step1:
[1623934398773]     //XPath: //*[@resource-id='com.tal.tiku:id/arg' and @text='请输入验证码']
[1623934398773]     //XPathExpression: org.apache.xpath.jaxp.XPathExpressionImpl@5a4c084
[1623934398774]     //Action: CLICK
[1623934398774]     //Text: 88888888
[1623934398775]     //Duration: 0
[1623934398775]     //Throttle: 1000
[1623934398775]   // Step2:
[1623934398776]     //XPath: //*[@resource-id='com.tal.tiku.id/arg' and @class='android.widget.LinearLayout']
[1623934398776]     //XPathExpression: org.apache.xpath.jaxp.XPathExpressionImpl@3e6606d
[1623934398777]     //Action: CLICK
[1623934398777]     //Text:
[1623934398778]     //Duration: 0
[1623934398778]     //Throttle: 1000
[1623934398779]   // Step3:
[1623934398779]     //XPath: //*[@resource-id='com.tal/tiku:id/arg' and @text='登 录']
[1623934398779]     //XPathExpression: org.apache.xpath.jaxp.XPathExpressionImpl@bc674a2
[1623934398780]     //Action: CLICK
[1623934398781]     //Text:
[1623934398781]     //Duration: 0
[1623934398782]     //Throttle: 1000
[1623934398788] // Black Widget:
[1623934398789] // Widget0:
[1623934398790] //   Activity: com.tal.user.login.CodeLoginActivity
[1623934398790] //   Xpath: //*[@resource-id='com.tal.tiku:id/arg' and @text='密码登录']
[1623934398791] //   Index: 0
[1623934398792] // Widget0:
[1623934398792] //   Activity: com.tal.user.login.CodeLoginActivity
[1623934398793] //   Xpath: //*[@resoutce-id='com.tal.tiku:id/arg' and @text='获取验证码']
[1623934398793] //   Index: 0
[1623934398793] // Widget0:
[1623934398794] //   Activity: com.tal.user.login.CodeLoginActivity
[1623934398794] //   Xpath: //*[@resource-id='com.tal.tiku:id/arg' and @text='《用户协议》']
[1623934398795] //   Index: 0
[1623934398795] // Widget0:
[1623934398796] //   Activity: com.tal.user.login.CodeLoginActivity
[1623934398796] //   Xpath: //*[@resource-id='com.tal.tiku.id/arg' and @text='《隐私政策》']
[1623934398797] //   Index: 0
[1623934398797] // Widget0:
[1623934398798] //   Activity: com.tal.user.login.CodeLoginActivity
[1623934398798] //   Xpath: //*[@resource-id='com.tal.tiku.id/arg']
[1623934398799] //   Index: 0
[1623934398799] //   Bounds: [604,478]
[1623934398799] // Widget0:
[1623934398800] //   Activity: com.tal.user.login.CodeLoginActivity
[1623934398800] //   Xpath: //*[@resource-id='com.tal.tiku.id/arg']
[1623934398800] //   Index: 0
[1623934398801] //   Bounds: [448,593]
[1623934401333]

[1623934401346] // the top activity is com.huawei.android.launcher.unihome.UniHomeLauncher, not testing app, need inject restart app
[1623934401349] fastbot exec shell:
[1623934401353] fastbot exec schema:
[1623934401354] Switch : #Intent;action=android.intent.action.MAIN;category=android.intent.category.LAUNCHER;launchFlags=0x10200000;component=com.tal.tiku/.splash.SplashActivity;end
[1623934401382]     // Allowing start of Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.tal.tiku/.splash.SplashActivity } in package com.tal.tiku
[1623934401556] : debug, currentActivity is com.tal.tiku.splash.SplashActivity
[1623934401557] Sleep for 0 ms
[1623934401561] Sleep for 2000 ms
[1623934403565] Sleep for 0 ms
[1623934403567] :schema :
[1623934403576] Sleep for 0 ms
[1623934403578] Sleep for 2000 ms
[1623934404413]     // Allowing start of Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.tal.tiku/.main.MainActivity } in package com.tal.tiku
[1623934404451]     // activityResuming(com.tal.tiku)
[1623934405583] : debug, currentActivity is com.tal.tiku.main.MainActivity
[1623934405584] Sleep for 0 ms
[1623934405592] Sleep for 600 ms
[1623934406194] Sleep for 0 ms
[1623934410358] Exception for get action resouece: g0a7@CLICKWidget{hashCode=-1860486566, index=2, clazz='android.widget.TextView', resourceId='com.tal.tiku:id/arg', operationTypeMask=6, scrollType=none, text='版本升级', contentDesc=''}[priority=0][throttle=200][, UNVISITED][saturation=(0.0,1)][bounds=(210,1386,510,1466)]
[1623934410362] Exception for get action resouece: g0a8@CLICKWidget{hashCode=-1076197662, index=1, clazz='android.widget.ImageView', resourceId='com.tal.tiku:id/arg', operationTypeMask=6, scrollType=none, text='', contentDesc=''}[priority=0][throttle=200][, UNVISITED][saturation=(0.0,1)][bounds=(620,964,680,1024)]
[1623934410379] Exception for get action resouece: g0a9@BACKg0s1@com.tal.tiku.main.MainActivity@50360232[priority=0][throttle=200][, UNVISITED]
[1623934410380] Exception for get action class: g0a9@BACKg0s1@com.tal.tiku.main.MainActivity@50360232[priority=0][throttle=200][, UNVISITED]
[1623934410381] *** Get guitree ***
[1623934410471]     <?xml version="1.0" encoding="UTF-8"?><node index="0" text="" resource-id="" class="android.widget.FrameLayout" content-desc="" package="com.tal.tiku" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" scroll-type="none" bounds="[0,924][720,1560]">
  <node index="0" text="升级到新版本" resource-id="com.tal.tiku:id/arg" class="android.widget.TextView" content-desc="" package="com.tal.tiku" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" scroll-type="none" bounds="[40,964][232,1007]"/>
  <node index="1" text="" resource-id="com.tal.tiku:id/arg" class="android.widget.ImageView" content-desc="" package="com.tal.tiku" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" scroll-type="none" bounds="[620,964][680,1024]"/>
  <node index="2" text="版本升级" resource-id="com.tal.tiku:id/arg" class="android.widget.TextView" content-desc="" package="com.tal.tiku" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" scroll-type="none" bounds="[210,1386][510,1466]"/>
  <node index="3" text="安装包已在WiF" resource-id="com.tal.tiku:id/arg" class="android.widget.TextView" content-desc="" package="com.tal.tiku" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" scroll-type="none" bounds="[207,1482][513,1520]"/>
</node>

[1623934410473] using nstep-q agent
[1623934410474] // Display Bounds: (0,924),(720,1560)
[1623934410474] // Monkey is over!
[1623934410475] :Sending rotation degree : 0, persist : false
[1623934410611] Running failed
java.lang.NumberFormatException: For input string: "[604"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:451)
	at java.lang.Float.valueOf(Float.java:416)
	at com.android.a.c.a.b.b(SourceFile:134)
	at com.android.a.c.a.b.a(SourceFile:1108)
	at com.android.a.a.e.ay(SourceFile:131)
	at com.android.a.a.c.ar(SourceFile:330)
	at com.android.a.a.e.c(SourceFile:10548)
	at com.android.a.a.b.b(SourceFile:236)
	at com.android.a.a.b.a(SourceFile:226)
	at com.android.commands.monkey.y.y(SourceFile:681)
	at com.android.commands.monkey.y.l(SourceFile:1259)
	at com.android.commands.monkey.Monkey.f(SourceFile:1861)
	at com.android.commands.monkey.Monkey.a(SourceFile:1105)
	at com.android.commands.monkey.Monkey.main(SourceFile:827)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
[1623934410615] Please report this bug issue to github

max.widget.black内容如下：
[
    {
        "activity": "com.tal.user.login.CodeLoginActivity",
        "xpath": "//*[@resource-id='com.tal.tiku:id/arg' and @text='密码登录']"
    },
    {
        "activity": "com.tal.user.login.CodeLoginActivity",
        "xpath": "//*[@resoutce-id='com.tal.tiku:id/arg' and @text='获取验证码']"
    },
    {
        "activity": "com.tal.user.login.CodeLoginActivity",
        "xpath": "//*[@resource-id='com.tal.tiku:id/arg' and @text='《用户协议》']"
    },
    {
        "activity": "com.tal.user.login.CodeLoginActivity",
        "xpath": "//*[@resource-id='com.tal.tiku.id/arg' and @text='《隐私政策》']"
    },
    {
        "activity": "com.tal.user.login.CodeLoginActivity",
        "xpath": "//*[@resource-id='com.tal.tiku.id/arg']",
        "bounds": "[604,478]"  // 尝试过 "bounds": [604,478]这种格式也不报错

    },
    {
        "activity": "com.tal.user.login.CodeLoginActivity",
        "xpath": "//*[@resource-id='com.tal.tiku.id/arg']",
        "bounds": "[448,593]"
    }
]

PDF使用文档对这块的使用描述较少，麻烦能补充一下吗？

**Comment by geron-cn** [comment]
bounds 是 左上，右下两个坐标，  4 个整数

**Comment by zhangzhao4444** [comment]
2.2.01.0824.1351-git 版本可以再试一下
