### ISSUE TITLE
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@939892already registered!

### ISSUE THREAD

**Issue by sadmenmen** [bytedance/Fastbot_Android#46]
Running failed
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@939892already registered!
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2384)
        at android.os.Parcel.createException(Parcel.java:2360)
        at android.os.Parcel.readException(Parcel.java:2343)
        at android.os.Parcel.readException(Parcel.java:2285)
        at android.view.accessibility.IAccessibilityManager$Stub$Proxy.registerUiTestAutomationService(IAccessibilityManager.java:739)
        at android.app.UiAutomationConnection.registerUiTestAutomationServiceLocked(UiAutomationConnection.java:456)
        at android.app.UiAutomationConnection.connect(UiAutomationConnection.java:106)
        at android.app.UiAutomation.connect(UiAutomation.java:243)
        at android.app.UiAutomation.connect(UiAutomation.java:219)
        at com.android.commands.monkey.y.connect(SourceFile:219)
        at com.android.commands.monkey.y.<init>(SourceFile:276)
        at com.android.commands.monkey.Monkey.a(SourceFile:1024)
        at com.android.commands.monkey.Monkey.main(SourceFile:827)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:463)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.accessibility.UiAutomationManager.registerUiTestAutomationServiceLocked(UiAutomationManager.java:97)
        at com.android.server.accessibility.AccessibilityManagerService.registerUiTestAutomationService(AccessibilityManagerService.java:870)
        at android.view.accessibility.IAccessibilityManager$Stub.onTransact(IAccessibilityManager.java:371)
        at android.os.Binder.execTransactInternal(Binder.java:1157)
        at android.os.Binder.execTransact(Binder.java:1126)

[1627979221474] Please report this bug issue to github

**Comment by geron-cn** [comment]
means UiAutomationService  has been used by other process，find the process or directly restart your phone can resolve this problem.

**Comment by zhangzhao4444** [comment]
非bug，请参考用户手册
