### ISSUE TITLE
Running failed java.lang.RuntimeException: android.os.DeadSystemException

### ISSUE THREAD

**Issue by 3xiaoxiao3** [bytedance/Fastbot_Android#48]
Running failed
[1628044934086] Please report this bug issue to github
java.lang.RuntimeException: android.os.DeadSystemException
        at android.hardware.input.InputManager.injectInputEvent(InputManager.java:909)
        at com.android.commands.monkey.q.a(SourceFile:227)
        at com.android.commands.monkey.Monkey.f(SourceFile:1863)
        at com.android.commands.monkey.Monkey.a(SourceFile:1105)
        at com.android.commands.monkey.Monkey.main(SourceFile:827)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
Caused by: android.os.DeadSystemException
        ... 7 more

**Comment by zhangzhao4444** [comment]
2.2.01.0824.1351-git版本已修改
