### ISSUE TITLE
java.lang.OutOfMemoryError: Failed to allocate a 106112 byte allocation with 99128 free bytes and 96KB until OOM, target footprint 134217728, growth limit 134217728

### ISSUE THREAD

**Issue by pingchaodeng** [bytedance/Fastbot_Android#49]
[1631182553764] *** Get guitree ***
[1631182559126] // Monkey is over!
[1631182559127] :Sending rotation degree : 0, persist : false
[1631182559167] Running failed
java.lang.OutOfMemoryError: Failed to allocate a 106112 byte allocation with 99128 free bytes and 96KB until OOM, target footprint 134217728, growth limit 134217728
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
	at java.lang.StringBuffer.toString(StringBuffer.java:671)
	at java.io.StringWriter.toString(StringWriter.java:210)
	at com.android.a.d.a.cc(SourceFile:170)
	at com.android.a.a.e.c(SourceFile:2263)
	at com.android.a.a.b.b(SourceFile:236)
	at com.android.a.a.b.a(SourceFile:226)
	at com.android.commands.monkey.y.y(SourceFile:681)
	at com.android.commands.monkey.y.l(SourceFile:1259)
	at com.android.commands.monkey.Monkey.f(SourceFile:1861)
	at com.android.commands.monkey.Monkey.a(SourceFile:1105)
	at com.android.commands.monkey.Monkey.main(SourceFile:827)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:463)
[1631182559170] Please report this bug issue to github

**Comment by yaming116** [comment]
java.lang.OutOfMemoryError: Failed to allocate a 31688 byte allocation with 2624 free bytes and 2624B until OOM, target footprint 268435456, growth limit 268435456
  at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
  at java.lang.StringBuffer.toString(StringBuffer.java:671)
  at java.io.StringWriter.toString(StringWriter.java:210)
  at com.android.a.d.a.cc(SourceFile:170)
  at com.android.a.a.e.c(SourceFile:2263)
  at com.android.a.a.b.b(SourceFile:236)
  at com.android.a.a.b.a(SourceFile:226)
  at com.android.commands.monkey.y.y(SourceFile:681)
  at com.android.commands.monkey.y.l(SourceFile:1259)
  at com.android.commands.monkey.Monkey.f(SourceFile:1861)
  at com.android.commands.monkey.Monkey.a(SourceFile:1105)
  at com.android.commands.monkey.Monkey.main(SourceFile:827)
  at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
  at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:339)

**Comment by geron-cn** [comment]
> related： #27

**Comment by zhangzhao4444** [comment]
2.2.01.0824.1351-git 版本已修复
