### ISSUE TITLE
Andorid6 requires INJECT_EVENTS permission

### ISSUE THREAD

**Issue by windanchaos** [bytedance/Fastbot_Android#5]
android6 的设备权限有关，貌似和Fastbot无关。
但是细细想一下，被测app的进程如果是fastbot的子进程的话应该就不存在这个问题吧。这个比较让人疑惑。
求指教。

[1608024374386] *** Inject event ***
[1608024374396] :Sending Touch (ACTION_DOWN): 0:(540.0,984.5)
[1608024374397]     // Injection Failed com.android.commands.monkey.E@f72519e
[1608024374398] :Sending Touch (ACTION_MOVE): 0:(540.0,984.5)
[1608024374399]     // Injection Failed com.android.commands.monkey.E@6bf147f
[1608024374400] Waiting Event for 20 milliseconds
[1608024374421] Sleep for 0 ms
[1608024374423] :Sending Touch (ACTION_MOVE): 0:(593.9,984.5)
[1608024374424]     // Injection Failed com.android.commands.monkey.E@d49c4c
[1608024374424] Waiting Event for 20 milliseconds
[1608024374445] Sleep for 0 ms
[1608024374446] :Sending Touch (ACTION_MOVE): 0:(647.8,984.5)
[1608024374447]     // Injection Failed com.android.commands.monkey.E@ede495
[1608024374448] Waiting Event for 20 milliseconds
[1608024374469] Sleep for 0 ms
[1608024374470] :Sending Touch (ACTION_MOVE): 0:(701.7,984.5)
[1608024374471]     // Injection Failed com.android.commands.monkey.E@12de9aa
[1608024374472] Waiting Event for 20 milliseconds
[1608024374492] Sleep for 0 ms
[1608024374493] :Sending Touch (ACTION_MOVE): 0:(755.6,984.5)
[1608024374494]     // Injection Failed com.android.commands.monkey.E@13a799b
[1608024374495] Waiting Event for 20 milliseconds
[1608024374515] Sleep for 0 ms
[1608024374516] :Sending Touch (ACTION_MOVE): 0:(809.5,984.5)
[1608024374517]     // Injection Failed com.android.commands.monkey.E@fd53138
[1608024374518] Waiting Event for 20 milliseconds
[1608024374539] Sleep for 0 ms
[1608024374539] :Sending Touch (ACTION_MOVE): 0:(863.4,984.5)
[1608024374540]     // Injection Failed com.android.commands.monkey.E@c153511
[1608024374541] Waiting Event for 20 milliseconds
[1608024374562] Sleep for 0 ms
[1608024374563] :Sending Touch (ACTION_MOVE): 0:(917.3,984.5)
[1608024374564]     // Injection Failed com.android.commands.monkey.E@758f676
[1608024374565] Waiting Event for 20 milliseconds
[1608024374586] Sleep for 0 ms
[1608024374587] :Sending Touch (ACTION_MOVE): 0:(971.2,984.5)
[1608024374589]     // Injection Failed com.android.commands.monkey.E@13d1477
[1608024374589] Waiting Event for 20 milliseconds
[1608024374610] Sleep for 0 ms
[1608024374611] :Sending Touch (ACTION_MOVE): 0:(1025.1,984.5)
[1608024374612]     // Injection Failed com.android.commands.monkey.E@e4828e4
[1608024374613] Waiting Event for 20 milliseconds
[1608024374634] Sleep for 0 ms
[1608024374634] :Sending Touch (ACTION_UP): 0:(1079.0,984.5)
[1608024374636]     // Injection Failed com.android.commands.monkey.E@587114d
[1608024374637] Sleep for 0 ms
[1608024374638] Sleep for 1000 ms
[1608024375640] Sleep for 0 ms
[1608024375649] :Send Key (ACTION_DOWN): 187    // KEYCODE_APP_SWITCH
[1608024375652] // Monkey is over!
[1608024375652] :Sending rotation degree : 0, persist : false
[1608024375667] Running failed
java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
	at android.os.Parcel.readException(Parcel.java:1620)
	at android.os.Parcel.readException(Parcel.java:1573)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(IInputManager.java:434)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:798)
	at com.android.commands.monkey.p.a(SourceFile:132)
	at com.android.commands.monkey.Monkey.f(SourceFile:1863)
	at com.android.commands.monkey.Monkey.a(SourceFile:1105)
	at com.android.commands.monkey.Monkey.main(SourceFile:827)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:332)

**Comment by zhangzhao4444** [comment]
设置里打开下模拟点击

**Comment by windanchaos** [comment]
> 设置里打开下模拟点击

谢谢。android6 小米是   开发者选项--调试栏，选择USB调试(安全设置），开启模拟点击。
