### ISSUE TITLE
执行报错

### ISSUE THREAD

**Issue by tuerkyNeo** [bytedance/Fastbot_Android#57]
[1630311310855] Running failed
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@54497c8already registered!
	at android.os.Parcel.createException(Parcel.java:2098)
	at android.os.Parcel.readException(Parcel.java:2058)
	at android.os.Parcel.readException(Parcel.java:2006)
	at android.view.accessibility.IAccessibilityManager$Stub$Proxy.registerUiTestAutomationService(IAccessibilityManager.java:642)
	at android.app.UiAutomationConnection.registerUiTestAutomationServiceLocked(UiAutomationConnection.java:451)
	at android.app.UiAutomationConnection.connect(UiAutomationConnection.java:101)
	at android.app.UiAutomation.connect(UiAutomation.java:241)
	at android.app.UiAutomation.connect(UiAutomation.java:217)
	at com.android.commands.monkey.y.connect(SourceFile:219)
	at com.android.commands.monkey.y.<init>(SourceFile:276)
	at com.android.commands.monkey.Monkey.a(SourceFile:1024)
	at com.android.commands.monkey.Monkey.main(SourceFile:827)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.accessibility.UiAutomationManager.registerUiTestAutomationServiceLocked(libmapleservices.so:8210760)
	at com.android.server.accessibility.AccessibilityManagerService.registerUiTestAutomationService(libmapleservices.so:8212908)
	at android.view.accessibility.IAccessibilityManager$Stub.onTransact(libmapleframework.so:4314020)
	at android.os.Binder.execTransactInternal(libmapleframework.so:6246396)
	at android.os.Binder.execTransact(libmapleframework.so:6248192)
callee: null 2001/4534

[1630311310857] Please report this bug issue to github

**Comment by geron-cn** [comment]
> related: #46
