### ISSUE TITLE
执行报错

### ISSUE THREAD

**Issue by zhaoch2014** [bytedance/Fastbot_Android#58]
java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@a978f4balready registered!
        at android.os.Parcel.createException(Parcel.java:1958)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.view.accessibility.IAccessibilityManager$Stub$Proxy.registerUiTestAutomationService(IAccessibilityManager.java:409)
        at android.app.UiAutomationConnection.registerUiTestAutomationServiceLocked(UiAutomationConnection.java:399)
        at android.app.UiAutomationConnection.connect(UiAutomationConnection.java:97)
        at android.app.UiAutomation.connect(UiAutomation.java:234)
        at android.app.UiAutomation.connect(UiAutomation.java:210)
        at com.android.commands.monkey.y.connect(SourceFile:219)
        at com.android.commands.monkey.y.<init>(SourceFile:276)
        at com.android.commands.monkey.Monkey.a(SourceFile:1024)
        at com.android.commands.monkey.Monkey.main(SourceFile:827)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.accessibility.UiAutomationManager.registerUiTestAutomationServiceLocked(UiAutomationManager.java:88)
        at com.android.server.accessibility.AccessibilityManagerService.registerUiTestAutomationService(AccessibilityManagerService.java:797)
        at android.view.accessibility.IAccessibilityManager$Stub.onTransact(IAccessibilityManager.java:159)
        at android.os.Binder.execTransact(Binder.java:731)

**Comment by zhaoch2014** [comment]
![image](https://user-images.githubusercontent.com/22072021/131985911-a78cf64b-e560-4efc-9058-45d04a9fb15f.png)

**Comment by zhaoch2014** [comment]
![image](https://user-images.githubusercontent.com/22072021/131986478-3846b6bf-cd9d-451a-9b8b-104fad2d7467.png)
黑控件配置

**Comment by zhangzhao4444** [comment]
看下手册中q&a
