### ISSUE TITLE
运行报错OOM啦

### ISSUE THREAD

**Issue by shersty** [bytedance/Fastbot_Android#63]
[1631791016838] Exception for get action resouece: g405a384428@BACKg0s3@com.miui.tsmclient.ui.CardListActivity@-1068202336[priority=1][throttle=0][]
[1631791016842] Exception for get action class: g405a384428@BACKg0s3@com.miui.tsmclient.ui.CardListActivity@-1068202336[priority=1][throttle=0][]
[1631791016845] *** Get guitree ***
[1631791035085] // Monkey is over!
[1631791035085] :Sending rotation degree : 0, persist : false
[1631791035115] Running failed
java.lang.OutOfMemoryError: Failed to allocate a 31680 byte allocation with 3392 free bytes and 3392B until OOM, target footprint 268435456, growth limit 268435456
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
	at java.lang.StringBuffer.toString(StringBuffer.java:671)
	at java.io.StringWriter.toString(StringWriter.java:210)
	at com.android.a.d.a.cc(SourceFile:170)
	at com.android.a.a.e.c(SourceFile:2263)
	at com.android.a.a.b.b(SourceFile:236)
	at com.android.a.a.b.a(SourceFile:226)
	at com.android.commands.monkey.y.y(SourceFile:681)
	at com.android.commands.monkey.y.l(SourceFile:1259)
	at com.android.commands.monkey.Monkey.f(SourceFile:1861)
	at com.android.commands.monkey.Monkey.a(SourceFile:1105)
	at com.android.commands.monkey.Monkey.main(SourceFile:827)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
[1631791036026] Please report this bug issue to github

**Comment by geron-cn** [comment]
拉最新版本没有这个问题的，  注意下 readme 中的 usage 有修改哈。
