### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by journey1989** [bytedance/Fastbot_Android#65]
[Fastbot][2021-09-17 15:44:28.988] // phone info： vivo_vivo X20_8.1.0
[Fastbot][2021-09-17 15:44:28.988] // runing fastbot
[Fastbot][2021-09-17 15:44:29.065] InputMethod ID: com.sohu.inputmethod.sogou.vivo/.SogouIME
[Fastbot][2021-09-17 15:44:29.078] // device serial number is 9523d12
[Fastbot][2021-09-17 15:44:29.111] // device uuid is 83277bb9-266c-4a83-81da-2579aa0eddb8
[Fastbot][2021-09-17 15:44:39.514]

[Fastbot][2021-09-17 15:44:39.518] // current activity is com.dubmic.app.page.index.IndexActivity
[Fastbot][2021-09-17 15:44:39.562] // Eventid: 1
[Fastbot]*** ERROR *** Error: Could not load library!
java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/local/tmp/arm64-v8a/libfastbot_native.so" not found
	at java.lang.Runtime.load0(Runtime.java:928)
	at java.lang.System.load(System.java:1621)
	at com.bytedance.fastbot.AiClient.<clinit>(SourceFile:41)
	at com.bytedance.fastbot.AiClient.l(SourceFile:110)
	at com.android.commands.monkey.x.A(SourceFile:814)
	at com.android.commands.monkey.x.k(SourceFile:389)
	at com.android.commands.monkey.Monkey.f(SourceFile:1501)
	at com.android.commands.monkey.Monkey.a(SourceFile:860)
	at com.android.commands.monkey.Monkey.main(SourceFile:454)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:372)
[Fastbot][2021-09-17 15:44:39.594] // Error: Could not load native library!
[Fastbot][2021-09-17 15:44:39.595] Please report this bug issue to github

**Comment by journey1989** [comment]
把libs的arm64-v8a push sdcard又报下面的错误：
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/GsonBuilder;
	at com.android.commands.monkey.fastbot.client.GsonIface.<clinit>(SourceFile:28)
	at com.android.commands.monkey.fastbot.client.Operate.fromJson(SourceFile:44)
	at com.bytedance.fastbot.AiClient.l(SourceFile:1130)
	at com.android.commands.monkey.x.A(SourceFile:814)
	at com.android.commands.monkey.x.k(SourceFile:389)
	at com.android.commands.monkey.Monkey.f(SourceFile:1501)
	at com.android.commands.monkey.Monkey.a(SourceFile:860)
	at com.android.commands.monkey.Monkey.main(SourceFile:454)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:372)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.gson.GsonBuilder" on path: DexPathList[[zip file "/sdcard/monkeyq.jar", zip file "/sdcard/framework.jar"],nativeLibraryDirectories=[/system/lib64, /system/vendor/lib64, /system/vendor/lib64/hw, /system/lib64, /system/vendor/lib64, /system/vendor/lib64/hw]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 10 more
[Fastbot][2021-09-17 15:49:49.219] Please report this bug issue to github

**Comment by geron-cn** [comment]
> 把libs的arm64-v8a push sdcard又报下面的错误：
> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/GsonBuilder;
> at com.android.commands.monkey.fastbot.client.GsonIface.(SourceFile:28)
> at com.android.commands.monkey.fastbot.client.Operate.fromJson(SourceFile:44)
> at com.bytedance.fastbot.AiClient.l(SourceFile:1130)
> at com.android.commands.monkey.x.A(SourceFile:814)
> at com.android.commands.monkey.x.k(SourceFile:389)
> at com.android.commands.monkey.Monkey.f(SourceFile:1501)
> at com.android.commands.monkey.Monkey.a(SourceFile:860)
> at com.android.commands.monkey.Monkey.main(SourceFile:454)
> at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
> at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:372)
> Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.gson.GsonBuilder" on path: DexPathList[[zip file "/sdcard/monkeyq.jar", zip file "/sdcard/framework.jar"],nativeLibraryDirectories=[/system/lib64, /system/vendor/lib64, /system/vendor/lib64/hw, /system/lib64, /system/vendor/lib64, /system/vendor/lib64/hw]]
> at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> ... 10 more
> [Fastbot][2021-09-17 15:49:49.219] Please report this bug issue to github

2021.09 版本 readme 中的 usage 有更新哈， 请安装步骤操作即可：
![image](https://user-images.githubusercontent.com/1511316/133747430-5b0b191f-125c-4792-b1d6-bc4c7e726205.png)
