### ISSUE TITLE
黑名单中配置bounds ，提示错误java.lang.NumberFormatException: For input string: "[270"

### ISSUE THREAD

**Issue by HannahShen** [bytedance/Fastbot_Android#79]
[fastbot.log](https://github.com/bytedance/Fastbot_Android/files/7315477/fastbot.log)

日志打印：
[1633777891254] using nstep-q agent
[1633777891254] // Display Bounds: (0,0),(1080,2400)
[1633777891307] // Monkey is over!
[1633777891308] :Sending rotation degree : 0, persist : false
[1633777891335] Running failed
java.lang.NumberFormatException: For input string: "[270"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.lang.Float.parseFloat(Float.java:451)
        at java.lang.Float.valueOf(Float.java:416)
        at com.android.a.c.a.b.b(SourceFile:134)
        at com.android.a.c.a.b.a(SourceFile:1108)
        at com.android.a.a.e.ay(SourceFile:131)
        at com.android.a.a.c.ar(SourceFile:330)
        at com.android.a.a.e.c(SourceFile:10548)
        at com.android.a.a.b.b(SourceFile:236)
        at com.android.a.a.b.a(SourceFile:226)
        at com.android.commands.monkey.y.y(SourceFile:681)
        at com.android.commands.monkey.y.l(SourceFile:1259)
        at com.android.commands.monkey.Monkey.f(SourceFile:1861)
        at com.android.commands.monkey.Monkey.a(SourceFile:1105)
        at com.android.commands.monkey.Monkey.main(SourceFile:827)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:420)
[1633777891346] Please report this bug issue to github

**Comment by zhangzhao4444** [comment]
bounds格式：“左相对百分比,顶,右,底”，例如： "bounds": "0.2,0.3,0.5,0.9"
下版本也兼容下老格式
