### ISSUE TITLE
运行后提示org.json.JSONException: Value at 3 is null.

### ISSUE THREAD

**Issue by RealMay** [bytedance/Fastbot_Android#8]
输入参数：adb -s XPL0220910005847 shell CLASSPATH=/sdcard/monkeyq.jar:/sdcard/framework.jar exec app_process /system/bin com.android.commands.monkey.Monkey -p com.xx.xxx --agent robot --running-minutes 5 --throttle 600 -v -v

报以下错误：
org.json.JSONException: Value at 3 is null.
        at org.json.JSONArray.get(JSONArray.java:291)
        at org.json.JSONArray.getJSONObject(JSONArray.java:523)
        at com.android.a.c.a.g.b(SourceFile:82)
        at com.android.a.c.a.g.b(SourceFile:56)
        at com.android.a.c.a.f.<clinit>(SourceFile:70)
        at com.android.a.c.a.f.dump(Unknown Source:0)
        at com.android.commands.monkey.Monkey.a(SourceFile:1022)
        at com.android.commands.monkey.Monkey.main(SourceFile:827)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

**Comment by zhangzhao4444** [comment]
有使用max.xpath.actions 配置吗？ log打印json error

**Comment by zhangzhao4444** [comment]
2.2.1.0304.2039_git 已修改
