### ISSUE TITLE
后台运行appium后，再执行fastbot，会报错error

### ISSUE THREAD

**Issue by luoting0323** [bytedance/Fastbot_Android#80]
起因是为了使用【自定义时间序列】功能，所以使用appium去查看空间信息，写完配置文件之后，就去执行fastbot运行monkey，
看到报错如下，【关闭appium后执行fastbot可正常运行】。请问，此问题是否需要关注～

> java.lang.IllegalStateException:`` UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@6a9824balready registered!

	at android.os.Parcel.createException(Parcel.java:2079)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.view.accessibility.IAccessibilityManager$Stub$Proxy.registerUiTestAutomationService(IAccessibilityManager.java:642)
	at android.app.UiAutomationConnection.registerUiTestAutomationServiceLocked(UiAutomationConnection.java:451)
	at android.app.UiAutomationConnection.connect(UiAutomationConnection.java:101)
	at android.app.UiAutomation.connect(UiAutomation.java:241)
	at android.app.UiAutomation.connect(UiAutomation.java:217)
	at com.android.commands.monkey.y.connect(SourceFile:219)
	at com.android.commands.monkey.y.<init>(SourceFile:276)
	at com.android.commands.monkey.Monkey.a(SourceFile:1024)
	at com.android.commands.monkey.Monkey.main(SourceFile:827)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.accessibility.UiAutomationManager.registerUiTestAutomationServiceLocked(libmapleservices.so:7321292)
	at com.android.server.accessibility.AccessibilityManagerService.registerUiTestAutomationService(libmapleservices.so:7323352)
	at android.view.accessibility.IAccessibilityManager$Stub.onTransact(libmapleframework.so:3019716)
	at android.os.Binder.execTransactInternal(libmapleframework.so:5523096)
	at android.os.Binder.execTransact(libmapleframework.so:5522308)

[1634025149116] Please report this bug issue to github

**Comment by zhangzhao4444** [comment]
受Android 底层限制，两者不可同时运行，Q&A中有相同问题解答
