### ISSUE TITLE
执行报错，java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/GsonBuilder;

### ISSUE THREAD

**Issue by Genius-LG** [bytedance/Fastbot_Android#94]
[Fastbot][2021-10-28 09:08:43.505] // current activity is com.huawei.camera.controller.CameraActivity
[Fastbot][2021-10-28 09:08:43.516] Sleeping for 2000 milliseconds
[Fastbot][2021-10-28 09:08:45.557] // Eventid: 3
[Fastbot][2021-10-28 09:08:45.577] fastbot native : library load!
[Fastbot][2021-10-28 09:08:45.585] // Monkey is over!
[Fastbot][2021-10-28 09:08:45.586] :Sending rotation degree=0, persist=false
[Fastbot][2021-10-28 09:08:45.629] Internal error
[Fastbot][2021-10-28 09:08:45.631] Please report this bug issue to github
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/GsonBuilder;
        at com.android.commands.monkey.fastbot.client.GsonIface.<clinit>(SourceFile:28)
        at com.android.commands.monkey.fastbot.client.Operate.fromJson(SourceFile:44)
        at com.bytedance.fastbot.AiClient.l(SourceFile:1130)
        at com.android.commands.monkey.x.A(SourceFile:817)
        at com.android.commands.monkey.x.k(SourceFile:392)
        at com.android.commands.monkey.Monkey.f(SourceFile:1501)
        at com.android.commands.monkey.Monkey.a(SourceFile:860)
        at com.android.commands.monkey.Monkey.main(SourceFile:454)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:420)
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
        ... 10 more

**Comment by geron-cn** [comment]
详细参照 readme，需要push 3个 jar 和 几个so文件到手机中， 启动命令也有更新

**Comment by Genius-LG** [comment]
> 详细参照 readme，需要push 3个 jar 和 几个so文件到手机中， 启动命令也有更新

已解决
